src/commands/abstract_command.ts
- [Analytics] Log commands to server
- [Abstract Command] Check upgrade prompt
=> [Abstract Command] Check upgrade prompt

src/wrapper-classes/branch.ts
- [Sanity Check] No Current Branch
- [Sanity Check] No Current Branch - Detached Head
See comment in changed file.
=> [Sanity Check] No Current Branch (Detached Head)

.husky/pre-commit, package.json, yarn.lock
- [Husky] Add support
- Improve linting message
=> gf  add husky

package.json, src/commands/original-commands/submit/index.ts, src/lib/utils/index.ts, src/lib/utils/splog.ts, yarn.lock
MVP submit command.
This implementation:
* submits all of the downstack (inclusive) PRs from the current head
Known limitations that we'll want to fix up in coming PRs:
* uses a placeholder PR title ("Merge [head] into [base]")
* we can be smarter and try to infer a title from the commit messages
* doesn't store the information it gets back from the server about the PR 
* we can use this info later to make fewer queries when showing relevant information on the log command
* submits everything as request to create a PR (handling this on the server if the PR already exists)
* if we have info locally about the PR tied to a branch, we can just update rather than waiting to handle the exception and then trigger a new request on the server
* doesn't let the user configure the placeholder title
=> [Submit] Submit current + all downstack branches

src/actions/submit.ts, src/wrapper-classes/branch.ts, src/wrapper-classes/commit.ts
The PR inferred the title from this commit!
=> [Submit] Infer Title if Single Commit

src/actions/fix.ts
Even in the demo (with 7 total branches) the restack output is too large to be useful, and frequently people comment that it's confusing to them. This is an approach to simplify it that updates the output to be a list of direct children which were restacked and any descendants modified: 
```
tomasreimers@Tomass-MBP-2 tmp-99121-Uypst70R4XJG % gp branch amend -m "Files"
Restacked:
- tr--review_queue_server (1 descendent)
```
=> Update the restack output to be more readable

src/actions/print_stack.ts, src/lib/utils/time.ts, src/wrapper-classes/branch.ts, src/wrapper-classes/commit.ts
=> [Log] Show time since branch tip last updated

src/actions/submit.ts, src/wrapper-classes/branch.ts
https://linear.app/screenplay/issue/SP-1385/submit-dont-create-empty-prs
=> [Submit] Don't submit empty branches

src/actions/submit.ts, src/wrapper-classes/branch.ts
https://linear.app/screenplay/issue/SP-1302/inactionable-auth-error
Improving error output for:
* auth errors
* generic, unknown errors
=> [Submit] Better auth error/unknown error handling

src/commands/stacks.ts
This PR improves our `gp stacks` perf using the same techniques as with `gp log`. After the changes downstack, we now have overall sources of truth for 1) the max number of days we should search behind trunk and 2) the max number of stacks we should search behind trunk.
In this PR, we change how we query branch lineage to account for these settings.
Eventually — since this functionality is shared between `gp stacks` and `gp log` — this should be broken out into a shared utils file.
=> Optimize stacks perf

src/commands/repo-commands/pr_templates.ts, src/lib/utils/pr_templates.ts, test/fast/graphite_utils/pr_templates.ts, test/graphite_utils/pr_templates.ts
This PR adds a util class to find all GitHub PR templates within a give git repository as well as tests for said class.
=> [Submit] Find all PR templates

src/actions/validate.ts
=> [Validate] Fix some grammar

.github/PULL_REQUEST_TEMPLATE.md
**Context:**
(as titled)
Adding a PR template `graphite-cli`.
**Test Plan:**
This PR is created with the new template (and the downstack PRs).
=> Add PR template to graphite-cli

src/actions/submit.ts, src/lib/utils/pr_templates.ts
https://user-images.githubusercontent.com/9063972/129935423-56be65ca-d3bd-4826-b84b-99a5e6265a0f.mov
=> [Submit] Interactive mode

.CHANGELOG, package.json, src/lib/config/repo_config.ts, src/lib/preconditions/index.ts, test/fast/commands/branch/branch_create.test.ts
**Context:**
Willy reported having issues when he created a stack off "production" which was an ignored branch in his repo.
Update the branch precondition to check that you're not working off an ignored branch.
**Test Plan:**
Added a new fast test
=> fix(branch_create_bug): disallow working off an ignored branch

src/actions/interactive_checkout.ts, src/actions/stacks.ts, src/commands/branch-commands/checkout.ts, src/commands/log-commands/short.ts, src/commands/repo-commands/ignored_branches.ts, src/wrapper-classes/stack.ts
**Context:**
Make it easier to see ignored branches and add to them
=> feat(repo_ignore): command to ignore branches

src/actions/interactive_checkout.ts, src/actions/stacks.ts, src/commands/branch-commands/checkout.ts, src/commands/log-commands/short.ts, src/commands/repo-commands/ignored_branches.ts, src/commands/user-commands/tips.ts, src/lib/config/user_config.ts, src/lib/utils/index.ts, src/lib/utils/splog.ts, src/wrapper-classes/stack.ts
**Context:**
I want to start using "tips" more on some of our commands - lets make it configurable so that users can disable them once they feel expert enough.
=> feat(user_tips): add tips config

src/actions/interactive_checkout.ts, src/actions/stacks.ts, src/commands/branch-commands/checkout.ts, src/commands/log-commands/short.ts, src/commands/repo-commands/ignored_branches.ts, src/commands/user-commands/tips.ts, src/lib/config/user_config.ts, src/lib/utils/index.ts, src/lib/utils/splog.ts, src/wrapper-classes/branch.ts, src/wrapper-classes/stack.ts
**Context:**
Just some simple helper methods to use in future stacked PRs
=> util(branch): helper methods

src/actions/log_short.ts, src/wrapper-classes/abstract_stack_builder.ts
=> perf(memoization): stack builder use memoization

.github/workflows/premerge.yml, src/actions/fix.ts, src/actions/log_short.ts, src/actions/onto.ts, src/lib/git-refs/branch_ref.ts, src/lib/git-refs/branch_relations.ts, src/lib/git-refs/cache.ts, src/lib/git-refs/index.ts, src/lib/utils/index.ts, src/wrapper-classes/abstract_stack_builder.ts, src/wrapper-classes/branch.ts, src/wrapper-classes/git_stack_builder.ts, test/fast/actions/validate_action.test.ts, test/fast/commands/stack/clean.test.ts, test/lib/scenes/public_repo_scene.ts, test/lib/utils/configure_test.ts
**Context:**
I disabled slow tests earlier in the stack while optimising performance - this is me re-enabling them.
=> ci(slow): reenable slow tests

src/commands/log-commands/default.ts
=> chore(gp): change reference to gt

src/actions/log_short.ts
**Context:**
If a branch, mid stack, is untracked, we dont currently show a warning and tip. Let's fix that.
=> feat(ls): untracked branch warnings

src/lib/utils/ts_helpers.ts
Porting some TS helper code over from monologue.
=> Add TS helper class

src/actions/submit.ts
**Context:**
Right now, when a user runs submit on a stack of PRs, we pass all of them to the server and update all of the PRs — even if an update isn't strictly necessary. (i.e. None of the local PR fields — the PR base nor the PR code — have changed at all.)
Sashank flagged this as a confusing user experience (and it also wastes a few API requests). The proper fix here is to detect when a branch has changed and only then submit the PR.
To do so, we need to be able to tell if:
* the code has changed
* if it's base has changed (as opposed to the previous PR)
The next few PRs in the stack accomplish this.
The first thing that we'll tackle is determining whether the base has changed. To do this we need to:
* save the PR base on the prior submit
* compare …
=> [Submit] Thread both request and response through to output

src/actions/submit.ts, src/wrapper-classes/branch.ts
**Context:**
See #267.
In this PR, we take the info we threaded through in the previous PR and use it to save the submitted PR's base branch (for later reference).
=> [Submit] Save PR base branch in branch's PR info metadata

src/actions/submit.ts, src/commands/downstack-commands/submit.ts, src/commands/stack-commands/submit.ts
**Context:**
Add a new command that lets you submit just downstack. Reuse shared definitions with other submit command.
=> feat(submit): add downstack command

src/actions/submit.ts, src/commands/downstack-commands/submit.ts, src/commands/stack-commands/submit.ts, src/wrapper-classes/abstract_stack_builder.ts, test/fast/wrapper-classes/stack_builder.test.ts
**Context:**
Add helper function that makes it easier to capture a scoped stack
=> feat(stack_builder): downstack

src/wrapper-classes/stack.ts, test/fast/wrapper-classes/stack_builder.test.ts
**Context:**
Helper function which fetched topologically ordered branches from stack.
=> feat(stacks): to branches helper function

src/actions/submit.ts, src/wrapper-classes/stack.ts, test/fast/wrapper-classes/stack_builder.test.ts
**Context:**
Update submit to use StackBuilder for travering a stack depending on scope.
=> fix(submit): support scope correctly

src/actions/commit_amend.ts, src/actions/commit_create.ts
=> chore(warning): improve warning command

src/actions/submit.ts
**Context:**
you can't currently cntr-c out of a stack submit. Lets fix that
=> fix(submit): support killing midsubmit

src/actions/submit.ts
**Context:**
Alongside the github PR links, print a link back to app.graphite.dev to see the stacked PRs in the user's review queue.
=> feat(submit): backlink to app.graphite.dev

.github/CODEOWNERS
**Context:**
Make Neha a code owner on the CLI
=> chore(reviewers): add neha

src/commands/repo-commands/repo_sync.ts, test/fast/commands/repo/sync.test.ts
**Context:**
Self explanatory.
=> feat(sync): pull by default

src/actions/fix.ts, src/actions/onto.ts, src/commands/branch-commands/rename.ts, src/commands/repo-commands/repo_sync.ts, src/lib/config/cache.ts, src/lib/config/index.ts, src/lib/config/repo_config.ts, src/lib/git-refs/branch_ref.ts, src/lib/git-refs/branch_relations.ts, src/lib/git-refs/index.ts, src/lib/utils/index.ts, src/lib/utils/repo_root_path.ts, src/wrapper-classes/index.ts, src/wrapper-classes/metadata_ref.ts, test/fast/actions/validate_action.test.ts, test/fast/commands/repo/sync.test.ts, test/lib/utils/configure_test.ts
**Context:**
Centralize getting the repo root path, and cache once per execution
=> refactor(cache): cache repo root path

src/actions/submit.ts, src/commands/branch-commands/rename.ts, src/wrapper-classes/branch.ts, src/wrapper-classes/metadata_ref.ts
**Context:**
Branch class is a bit bloated, start moving some of the metadata_ref logic out.
=> refactor(metadata_ref): migrate logic from branch

src/actions/sync.ts, src/wrapper-classes/metadata_ref.ts, test/fast/commands/repo/sync.test.ts
**Context:**
Update sync to clear out outdated metadata refs to keep repos clean.
=> feat(sync): delete dangling metadata refs

src/actions/sync.ts
**Context:**
Improve the readability and organization of the sync action - no new functionality.
=> refactor(sync): no change in functionality

src/actions/sync.ts, test/fast/commands/repo/sync.test.ts
**Context:**
Unzit and fix a test.
=> fix(sync): unzit test and fix

src/actions/sync.ts, src/lib/preconditions/index.ts, test/fast/commands/repo/sync.test.ts
**Context:**
Im going to use this logic in multiple files, so let's abstract it into a precondition.
=> util(preconditions): create auth precondition

src/actions/sync.ts, src/commands/repo.ts, src/lib/preconditions/index.ts, test/fast/commands/repo/sync.test.ts
**Context:**
I want to start writing "rs" for "repo sync".
=> feat(repo): add alias r

src/actions/submit.ts, src/actions/sync.ts, src/commands/repo.ts, src/lib/preconditions/index.ts, test/fast/commands/repo/sync.test.ts
**Context:**
Now that we have an auth precondition, let's clean up submit slightly.
=> refactor(submit): use auth precondition

src/actions/submit.ts, src/actions/sync.ts
**Context:**
Improve the power of "sync" by having it resubmit PR updates for branches with new merge bases.
=> feat(sync): resubmit prs with updated merge bases

src/actions/sync.ts
**Context:**
Fix a bug in prompting to delete a branch
=> fix(sync): correctly prompt

src/index.ts, src/lib/passthrough/index.ts
**Context:**
Many users have asked for passing through commands to git. Here is a bounded solution using warnings and an allowlist.
=> feat(passthough): forward some commands to git

src/actions/fix.ts, src/actions/interactive_checkout.ts, src/actions/next_or_prev.ts, src/actions/sync.ts, src/lib/utils/pr_templates.ts
**Context:**
Prompts doesnt support sigint kill by default, making it impossible not to continue through. Let's fix that.
=> fix(prompts): support killing mid prompt

src/actions/submit.ts, src/commands/branch-commands/submit.ts, src/commands/upstack-commands/submit.ts
**Context:**
Support the submit upstack and branch submit commands (we already do downstack and fullstack).
**Test Plan:**
Submitted the previous PR with branch submit, submitted this PR with upstack submit.
=> [Submit] Support upstack and branch

package.json, src/actions/print_stack.ts, src/index.ts, src/lib/telemetry/fetch_pr_info.ts, src/lib/telemetry/index.ts, src/wrapper-classes/metadata_ref.ts, yarn.lock
**Context:**
This PR:
* adds logic to fetch PR info from a server-side endpoint for each local PR created with Graphite
* we then render information such as the PR review status and the title
**Test Plan:**
| Before | After |
| -- | -- |
| <img width="539" alt="Screen Shot 2021-08-30 at 4 45 01 PM" src="https://user-images.githubusercontent.com/9063972/131410214-af457c6e-7345-48bc-9087-b814c0d6f32f.png"> | <img width="535" alt="Screen Shot 2021-08-30 at 4 44 39 PM" src="https://user-images.githubusercontent.com/9063972/131410222-757bce66-9612-458f-83a8-c9632d5530f0.png"> |
=> [Log] Show PR Info

src/actions/create_branch.ts
**Context:**
Im watching users create branches without commits and run into errors. Let's give them a tip to avoid this behavior.
=> docs(tip): guide users to use -m on branch create

src/actions/log_short.ts, src/actions/print_stack.ts
=> Don't print trunk as a child

src/commands/feedback-commands/default.ts, src/commands/feedback.ts
**Context:**
Reorganize feedback into a directory-based command so we can add other verbs to it.
=> refactor(feedback): move into folder

package.json, src/commands/feedback-commands/debug_context.ts, src/commands/feedback-commands/default.ts, src/lib/debug-context/index.ts, src/lib/git-refs/branch_ref.ts, src/lib/git-refs/branch_relations.ts, src/lib/utils/git_repo.ts, test/fast/commands/feedback/debug_context.test.ts, yarn.lock
**Context:**
Update feedback to accept an argument to submit debug-context to servers
=> feat(feedback): include optional debug-context

src/actions/sync.ts, test/fast/commands/repo/sync.test.ts
**Context:**
I temporarily removed the code to clean metadata and resubmit bases, after a user flagged a potential bug. This PR is me bringing those changes back. Additions to the old code include:
* More tests
* clearing the cache between branch deletions
=> Merge gf--sync_revert_revert into main

src/lib/preconditions/index.ts
=> refactor(index): fix error message

src/actions/fix.ts
**Context:**
Clean up and typos
=> refactor(fix): typos and cleanup

src/actions/sync.ts
**Context:**
If a branch has been merged on GitHub, we can suggest to delete it in repo sync.
Note that this widens the branches that we suggest to delete a little bit. Specifically, if the local copy of the branch doesn't match the merged-in code, before we would've been conservative and avoided suggesting to delete; now we suggest to delete.
I think this is a reasonable tradeoff since 1) we make a suggestion and 2) my mental model is that in GitHub/git branch names aren't meant to be re-used.
As above.
**Test Plan:**
Merged branch in GitHub, run repo sync, gets deleted.
=> [Repo Sync] Delete branches merged on GitHub

package.json, src/actions/sync.ts, test/fast/commands/repo/sync.test.ts, yarn.lock
**Context:**
In repo sync, we now:
* pull
* fetch information for all branches (NEW)
* find the branches to delete
* find the branches to resubmit
This PR also modifies the associated repo sync, stubbing out the newly added branch information fetch, to fix the tests.
**Test Plan:**
yarn build
yarn test
=> [Repo Sync] Sync PR info in repo sync

src/actions/sync.ts
**Context:**
Noticed that on an old PR that was merged into another feature branch — and not trunk — that 1) the deletion copy was still saying that it was merged into trunk 2) suggesting that it should delete the branch.
My thinking here is that:
* we should still offer to delete the branch
* but we should be accurate that the branch was merged somewhere else
As above.
**Test Plan:**
Branch merged into feature branch now says so in the copy.
=> [Repo Sync] Refine inferred base branch for merged branch

src/actions/sync.ts, test/fast/commands/repo/sync.test.ts
**Context:**
https://linear.app/screenplay/issue/SP-1735/[repo-sync]-repo-sync-doesnt-delete-branches-that-can-be-caught-by
This PR does 2 things:
1. When users supply the "force" argument to repo sync, it now also automatically affixes dangling branches to set their parent to trunk.
2. This means that previously dangling branches which repo sync skipped over in the deletion pass (because it only searched for branches off of trunk) are now caught in that pass. Added a test to confirm this behavior.
Big flag: this does run the risk of users running with force and repo sync attempting to set a branch behind trunk to now have its parent as trunk. Thoughts here?
**Test Plan:**
yarn test
=> [Repo Sync] Add force option to fix dangling branches

src/lib/preconditions/index.ts, src/lib/utils/git_status_utils.ts, test/fast/commands/branch/branch_create.test.ts
**Context:**
Improved command to detect untracked changes only
Changing the function to detect only untracked changeswq
=> refactor(utils): rename function and cleaner commands

src/lib/debug-context/index.ts
A couple of general improvements:
* print out how many commits there were in the original snapshotted repo and how many we've reconstructed to give an idea of how recreating the debug context is progressing
* if not all of a given commits parents have been created yet, requeue the commit
* this notably fixes a lot of the errors we were seeing before with things being `undefined` or errors with how we were using `-p`
* if we've processed a commit before, skip it
Payoff/testing: before adding these fixes, recreating the debug context for Jonas always failed; now it succeeds.
=> [Debug Context] Various fixes

src/lib/debug-context/index.ts
**Context:**
When recreating a debug context, we initialize a new repo and add all of the commits/branches from the snapshot. However, critically, we skip any branches which already exist in the new repo.
This means that if the snapshotted trunk was also named `main`, we skip actually adding a `main` branch that points to the user's correct main.
* Change the default name of the new repo's trunk and then delete it afterwards.
* Warn during re-create if we skip any branches.
* Delete the temporary new repo trunk and checkout the user's main afterwards.
**Test Plan:**
Hit this error when recreating Tomas's debug context; now that recreates successfully.
=> [Debug Context] Better handling of trunks named main

src/lib/debug-context/index.ts
=> [Debug Context] Capture current branch, checkout on recreation

src/actions/sync.ts
Adding some print statements to show what's happening in repo sync.
Again, in the happy path this doesn't matter but on bloated repos where this is being run for the first time, this is a valuable indicator that `gt repo sync` is doing work and is not hanging.
=> [Repo Sync] Add comments to indicate progress

src/commands/repo-commands/repo_trunk.ts
=> [Repo Config] Add gt repo trunk --set

src/actions/submit.ts
**Context:**
As titled.
As titled.
**Test Plan:**
tried to submit main, saw the error
=> [Submit] More clearly flag if submit fails because no parent for branch

src/wrapper-classes/branch.ts
There are 4 big operations we do:
* calculate the git parent for a branch
* calculate the git children for a branch
* calculate the meta parent for a branch
* calculate the meta children for a branch
1 and 2 are already memoized.
3 is fairly lightweight; this is static metadata.
This PR memoized the 4th operation.
=> [Perf] Memoize children from meta calculations

test/fast/commands/repo/sync.test.ts, test/fast/wrapper-classes/stack_builder.test.ts
=> Reenable tests

src/actions/fix.ts, src/wrapper-classes/abstract_stack_builder.ts, src/wrapper-classes/branch.ts
=> [Debug] Add debug output to stack fix paths

src/actions/create_branch.ts, src/actions/submit.ts, src/wrapper-classes/branch.ts, test/fast/commands/branch/branch_create.test.ts
**Context:**
We've talked about blocking on a network call before submit to verify that we have the most up-to-date information about a branch. This PR adds that change.
**Test Plan:**
tested locally
=> [Submit] Sync PR info before submit

src/actions/submit/submit.ts
Scattered throughout the submit action, we have logic that filters the submitted branches so that we don't submit trunk or re-submit an already-merged branch, for example.
This PR centralizes that logic.
=> [Submit] Refactor logic to get branches to submit

src/actions/submit/submit.ts
=> [Submit] More appearance tweaks

src/actions/submit/submit.ts, src/commands/branch-commands/submit.ts, src/commands/downstack-commands/submit.ts, src/commands/shared-commands/submit.ts, src/commands/stack-commands/submit.ts, src/commands/upstack-commands/submit.ts
For the feature request [here](https://graphite-community.slack.com/archives/C02DRNZELUU/p1633460166076300).
=> [Submit] Add dry-run option

src/lib/utils/git_repo.ts, test/fast/commands/commit/amend.test.ts, test/fast/commands/stack/fix_continue.test.ts
As titled — a test and some utils that will be shared in other tests added later.
=> [Continue] Add test for repo fix continue

src/actions/submit/submit.ts, src/lib/passthrough/index.ts, src/lib/telemetry/profile.ts, src/lib/telemetry/survey/survey.ts, src/lib/telemetry/tracer.ts, src/lib/utils/exec_sync.ts
Should fix local type errors when running `npm run build`.
=> Type try-catch errors with any

src/commands/branch-commands/submit.ts
**Context:**
In response to a user ask
Added a tip
**Test Plan:**
Existing tests
=> feat(submit): add tip on branch submit

src/commands/user-commands/tips.ts, src/lib/config/user_config.ts, test/fast/commands/user_config/tips.test.ts
=> fix(tips): allow  to disable tips

src/commands/branch-commands/next.ts, src/commands/branch-commands/prev.ts, test/fast/commands/branch/branch_traversal.test.ts
=> feat(branch traversal): up is next, down is prev

.CHANGELOG, package.json
=> Bump 0.16.3

.prettierignore, .prettierrc.json, package.json, yarn.lock
=> fix(prettier): add prettier to cli project

src/commands/user-commands/editor.ts, src/lib/utils/default_editor.ts
**Context:** Related to GT-2803 (https://linear.app/screenplay/issue/GT-2803/option-to-change-editor-preference-using-gt-user)
**Test Plan:**
:
=> fix(editorPref): don't print undefined, set and print default editor instead

src/actions/branch_traversal.ts
=> fix(traversal): correct log message

src/actions/fix_dangling_branches.ts, src/actions/init.ts, src/commands/repo-commands/ignored_branches.ts, src/lib/config/repo_config.ts
=> fix(ignored_branches): consolidate library functions

src/commands/repo-commands/ignored_branches.ts, src/lib/config/repo_config.ts, src/lib/preconditions/index.ts, test/fast/commands/repo/ignored_branches.test.ts
=> feat(ignore branches): option to remove ignored branches

src/actions/log_short.ts
=> fix(tip): fix language

README.md
**Context:**
Was hard to get environment set up. These instructions should make it easier in the future.
=> Update readme with instructions for developers

README.md
=> fix(README): update how to run test-one

src/actions/sync.ts
**Context:** https://graphite-community.slack.com/archives/C02DRNRA9RA/p1637773922203300?thread_ts=1637771042.201500&cid=C02DRNRA9RA
**Test Plan:**
:
=> fix(sync): update repo sync language

src/actions/submit/submit.ts
**Context:**
User requested enhancement: https://graphite-community.slack.com/archives/C02DRNZELUU/p1638573647341600
Respect the no-verify flag
**Test Plan:**
Test manually via a sample pre-push hook
=> fix(submit): respect the no-verify flag

src/actions/submit/submit.ts, src/actions/sync.ts, src/commands/branch-commands/submit.ts, src/commands/downstack-commands/submit.ts, src/commands/shared-commands/submit.ts, src/commands/stack-commands/submit.ts, src/commands/upstack-commands/submit.ts
=> fix(submit): support update-only option

src/actions/submit/submit.ts, src/actions/sync.ts, src/commands/branch-commands/submit.ts, src/commands/downstack-commands/submit.ts, src/commands/shared-commands/submit.ts, src/commands/stack-commands/submit.ts, src/commands/upstack-commands/submit.ts
**Context:**
User feedback that its not always clear to them why upstack/downstack branches are being updated with gt ss.
Add logging to provide more info
**Test Plan:**
Tested manually.
=> fix(submit): log when updating PRs

src/commands/repo-commands/repo_sync.ts
=> fix(repo sync): change language so not to mislead

src/actions/init.ts
=> fix(repo init): fix bug with null ignored branches

src/commands/branch-commands/parent.ts, src/lib/utils/validation_helper_message.ts
=> fix(doc): remove `branch parent --set` from tip

src/actions/submit/submit.ts
=> fix(submit): fix printing

src/commands/repo-commands/ignored_branches.ts, src/commands/repo-commands/repo_init.ts
=> fix(docs): fix ignore-branches doc

src/actions/submit/submit.ts, src/actions/validate.ts, src/wrapper-classes/abstract_stack_builder.ts, test/fast/actions/validate_action.test.ts
=> refactor(validate): validate the stack that is to be submitted

src/actions/submit/submit.ts
=> fix(submit): warn on closed and merged PRs

src/actions/submit/submit.ts
=> use --force-with-lease with submit

src/lib/utils/pr_templates.ts
=> fix: remove PR template ext restriction

.github/CODEOWNERS
=> cleanup(codeowners)

package.json
=> fix(cli): update homepage url to not talk about xcode projects

package.json, src/actions/submit/reviewers.ts, src/actions/submit/submit.ts, src/actions/sync.ts, src/commands/branch-commands/submit.ts, src/commands/downstack-commands/submit.ts, src/commands/shared-commands/submit.ts, src/commands/stack-commands/submit.ts, src/commands/upstack-commands/submit.ts, src/wrapper-classes/branch.ts, src/wrapper-classes/metadata_ref.ts, yarn.lock
=> feat(submit): include manually specify reviewers

scripts/installation/install_dev.sh, scripts/installation/install_nightly.sh, scripts/installation/install_stable.sh, scripts/installation/uninstall.sh
Add some simple scripts that encode what I normally just keep in my bash history.
=> util(scripts): add installation scripts

scripts/installation/install_dev.sh, scripts/installation/install_nightly.sh, scripts/installation/install_stable.sh, scripts/installation/uninstall.sh, src/actions/clean_branches.ts, src/actions/onto/current_branch_onto.ts, src/actions/onto/stack_onto.ts, src/commands/continue.ts, src/commands/upstack-commands/onto.ts, src/lib/utils/perform_in_tmp_dir.ts
`stack edit` will need to write a tmp file with edit instructions. Add this helper method to make it easier to work on temporary files.
=> util(tmp): make it easy to work in tmp dir

scripts/installation/install_dev.sh, scripts/installation/install_nightly.sh, scripts/installation/install_stable.sh, scripts/installation/uninstall.sh, src/actions/clean_branches.ts, src/actions/edit/apply_stack_edit_pick.ts, src/actions/edit/create_stack_edit_file.ts, src/actions/edit/edit_downstack.ts, src/actions/edit/parse_stack_edit_file.ts, src/actions/edit/stack_edits.ts, src/actions/onto/current_branch_onto.ts, src/actions/onto/stack_onto.ts, src/commands/continue.ts, src/commands/upstack-commands/onto.ts, src/lib/config/pending_stack_edits_config.ts, src/lib/utils/perform_in_tmp_dir.ts
Define the first `stackEdit` struct, a way to prompt for it from the user, and a way to save its progress to disk.
=> feat(edit): add the building blocks for stack edidt

scripts/installation/install_dev.sh, scripts/installation/install_nightly.sh, scripts/installation/install_stable.sh, scripts/installation/uninstall.sh, src/actions/clean_branches.ts, src/actions/edit/apply_stack_edit_pick.ts, src/actions/edit/create_stack_edit_file.ts, src/actions/edit/edit_downstack.ts, src/actions/edit/parse_stack_edit_file.ts, src/actions/edit/stack_edits.ts, src/actions/onto/current_branch_onto.ts, src/actions/onto/stack_onto.ts, src/commands/continue.ts, src/commands/downstack-commands/edit.ts, src/commands/upstack-commands/onto.ts, src/lib/config/pending_stack_edits_config.ts, src/lib/utils/perform_in_tmp_dir.ts
Using our building blocks, add `downstackEdit` to allow for reordering a branch.
Note: I know we're current missing tests, and support for lots of edge cases such as "what if a user writes a weird edit file, etc"
Testing this command is a little harder than normal due to the prompted file, so I'll work on that downstack. For now we can trust that it's unreleased, has no dependencies on it, and has been lightly manually tested (but we expect to iterate on it).
=> feat(edit): add command

src/actions/edit/create_stack_edit_file.ts
**Context:**
After reviewing with Nick, adjust the stack edit file and instruction comments.
=> style(edit): adjust edit file comments

package.json, src/actions/submit/pr_draft.ts, src/actions/submit/submit.ts, src/actions/sync.ts, src/commands/branch-commands/submit.ts, src/commands/downstack-commands/submit.ts, src/commands/stack-commands/submit.ts, src/commands/upstack-commands/submit.ts, yarn.lock
**Context:**
Update submit such that the draft flag toggles existing PRs, and not just new ones.
=> feat(submit): support undrafting

.CHANGELOG, package.json
=> chore(bump): v0.17.1

.CHANGELOG, package.json
=> chore(bump): 0.17.2

.github/workflows/premerge.yml
=> ci(slow_tests): remove because they've been failing

.github/workflows/premerge.yml
=> ci(linting): add super linter

.github/CODEOWNERS
=> chore(owners): change to team to include jacob

.github/workflows/premerge.yml
=> ci(superlinter): tune typescript linting

src/actions/create_branch.ts, src/actions/submit/submit.ts, src/commands/auth.ts, src/commands/user-commands/branch_prefix.ts, src/commands/user-commands/editor.ts, src/commands/user-commands/tips.ts, src/index.ts, src/lib/config/index.ts, src/lib/config/survey_config.ts, src/lib/config/user_config.ts, src/lib/context/context.ts, src/lib/debug-context/index.ts, src/lib/preconditions/index.ts, src/lib/sync/pr_info.ts, src/lib/telemetry/post_traces.ts, src/lib/telemetry/profile.ts, src/lib/telemetry/survey/post_survey.ts, src/lib/telemetry/survey/survey.ts, src/lib/utils/default_editor.ts, src/lib/utils/git_repo.ts, src/lib/utils/splog.ts, test/fast/commands/user_config/auth.test.ts, test/fast/commands/user_config/editor.test.ts, test/fast/commands/user_config/tips.test.ts, test/lib/scenes/abstract_scene.ts
=> refactor(user_config): move to retype

src/actions/commit_create.ts, src/actions/create_branch.ts, src/actions/edit/edit_downstack.ts, src/actions/log_short.ts, src/actions/submit/pr_body.ts, src/actions/submit/submit.ts, src/actions/sync.ts, src/commands/auth.ts, src/commands/branch-commands/submit.ts, src/commands/repo-commands/fix.ts, src/commands/user-commands/branch_prefix.ts, src/commands/user-commands/editor.ts, src/commands/user-commands/tips.ts, src/lib/config/survey_config.ts, src/lib/config/user_config.ts, src/lib/context/context.ts, src/lib/debug-context/index.ts, src/lib/preconditions/index.ts, src/lib/sync/pr_info.ts, src/lib/telemetry/post_traces.ts, src/lib/telemetry/survey/post_survey.ts, src/lib/telemetry/survey/survey.ts, src/lib/utils/default_editor.ts, src/lib/utils/git_repo.ts, src/lib/utils/splog.ts, test/fast/commands/repo_config/repo_config.test.ts, test/fast/commands/user_config/auth.test.ts, test/fast/commands/user_config/editor.test.ts, test/fast/commands/user_config/tips.test.ts
=> refactor(user_config): move to inject based context pattern

src/lib/config/compose_config.ts, src/lib/config/index.ts, src/lib/config/message_config.ts, src/lib/telemetry/upgrade_prompt.ts, test/fast/commands/user_config/message_config.test.ts
=> refactor(message_config): move to retype

.eslintrc
=> lint(imports): first rule

src/actions/clean_branches.ts, src/actions/commit_amend.ts, src/actions/commit_create.ts, src/actions/edit/apply_stack_edit_pick.ts, src/actions/edit/stack_edits.ts, src/actions/fix.ts, src/actions/onto/current_branch_onto.ts, src/actions/onto/stack_onto.ts, src/actions/sync.ts, src/commands/continue.ts, src/commands/repo-commands/fix.ts, src/commands/stack-commands/fix.ts, src/commands/upstack-commands/onto.ts, src/lib/config/compose_config.ts, src/lib/config/merge_conflict_callstack_config.ts, src/lib/context/context.ts, src/lib/errors/index.ts
**Context:**
Update the merge conflicts config to abide by retype, existing in the context, and also behave more like a normal stack.
=> refactor(merge_conficts): move to retype

src/actions/commit_amend.ts, src/actions/commit_create.ts, src/actions/edit/apply_stack_edit_pick.ts, src/actions/sync.ts, src/commands/continue.ts, src/commands/repo-commands/fix.ts, src/commands/stack-commands/fix.ts, src/commands/upstack-commands/onto.ts, src/lib/config/merge_conflict_callstack_config.ts
**Context:**
@nicholasyan, double check me on this? But I think we dont need this const.
=> refactor(merge_conflicts): remove top-of-stack frame type

src/actions/clean_branches.ts, src/actions/commit_amend.ts, src/actions/commit_create.ts, src/actions/edit/apply_stack_edit_pick.ts, src/actions/edit/stack_edits.ts, src/actions/fix.ts, src/actions/onto/current_branch_onto.ts, src/actions/onto/stack_onto.ts, src/actions/sync.ts, src/commands/continue.ts, src/commands/repo-commands/fix.ts, src/commands/stack-commands/fix.ts, src/commands/upstack-commands/onto.ts, src/lib/config/compose_config.ts, src/lib/config/merge_conflict_callstack_config.ts, src/lib/context/context.ts, src/lib/errors/index.ts, src/lib/utils/git_repo.ts, test/lib/scenes/abstract_scene.ts
**Context:**
Override the user_config location to a test dir for unit tests to ensure better parallelization, and less damage to the tester's env.
=> fix(ci): override user_config location for unit tests

src/commands/demo.ts
=> fix: cli demo origin

scripts/installation/install_nightly.sh, scripts/installation/install_stable.sh, src/commands/demo.ts, src/commands/repo-commands/repo_name.ts, src/commands/repo-commands/repo_owner.ts, src/lib/config/repo_config.ts, test/fast/commands/repo_config/repo_config.test.ts
=> update more references to screenplaydev in cli

.CHANGELOG, package.json
=> chore(bump): 0.17.4

src/actions/submit/reviewers.ts
=> fix(copy): minor spelling fix

src/commands/branch-commands/next.ts, src/commands/branch-commands/prev.ts
=> feat: add `u` and `d` as aliases for `up` and `down` commands

src/index.ts
=> fix: a typo

src/index.ts, src/lib/utils/signpost_deprecated_commands.ts
=> refactor: deprecation signpost to take the full command

src/actions/commit_amend.ts, src/actions/commit_create.ts, src/actions/create_branch.ts, src/lib/utils/addAll.ts
=> refactor: util function for calling add all

src/commands/branch-commands/next.ts, src/commands/branch-commands/prev.ts, src/index.ts, src/lib/utils/signpost_deprecated_commands.ts
=> feat: add deprecation signpost for bn/bp rename

src/commands/branch-commands/delete.ts, src/lib/utils/preprocess_command.ts, test/fast/commands/branch/branch_delete.test.ts
=> feat: change branch delete shortcut from bd to bdl (as bd is now branch down)

src/actions/delete_branch.ts, src/commands/branch-commands/delete.ts, src/lib/utils/preprocess_command.ts, test/fast/commands/branch/branch_delete.test.ts
=> feat: add hint about -D for gt bdl

scripts/installation/uninstall.sh
**Context:** uninstall script didn't uninstall public npm install
**Changes In This Pull Request:** now it does
**Test Plan:** ran it
=> chore(scripts): fix uninstall script

src/lib/config/compose_config.ts, src/lib/config/merge_conflict_callstack_config.ts, test/fast/configs/merge_conflict_callstack_config.test.ts
**Context:**
in response to this bug report: https://graphite-community.slack.com/archives/C02DRNRA9RA/p1648506004927579
=> fix(config): support remove on invalid

.CHANGELOG, package.json, src/lib/config/compose_config.ts, src/lib/config/merge_conflict_callstack_config.ts, test/fast/configs/merge_conflict_callstack_config.test.ts
=> chore(bump): 0.17.6

scripts/installation/develop.sh
=> chore: add convenience script for development

scripts/installation/develop.sh, src/lib/config/repo_config.ts, src/lib/requests/fetch_pr_info.ts
=> fix: background process for fetch_pr_info

scripts/installation/develop.sh, src/actions/commit_amend.ts, src/actions/commit_create.ts, src/actions/fix.ts, src/commands/shared-commands/fix.ts, src/commands/upstack-commands/fix.ts, test/fast/commands/upstack/fix.test.ts
=> feat: add upstack fix command and change scope for commit/amend fixes to be upstack

.CHANGELOG, package.json
=> chore(bump): 0.17.7

.CHANGELOG, src/commands/autocomplete.ts
=> fix: completions (to be included in 0.17.7)

.CHANGELOG, package.json, src/lib/requests/fetch_pr_info.ts, src/lib/telemetry/post_traces.ts, src/lib/telemetry/survey/post_survey.ts, src/lib/telemetry/upgrade_prompt.ts, src/lib/utils/spawn.ts
=> fix: CLI hangs and bump to 0.17.8

src/lib/telemetry/survey/post_survey.ts
=> fix: import

src/actions/branch_traversal.ts, src/commands/branch-commands/next.ts, src/commands/branch-commands/prev.ts
=> refactor: rename Next and Previous to Up and Down internally

src/actions/create_branch.ts
=> feat: display message when an empty commit is created by graphite

src/actions/submit/submit.ts, src/commands/repo-commands/repo_remote.ts, src/lib/config/repo_config.ts, src/lib/utils/trunk.ts
=> feat: allow configuration of remote

src/actions/create_branch.ts
Also cleaned up this function a little, think it reads easier now.  Note that we now always add the date between the prefix and the message -- we used to not add it if the message was nearing max branch length, but now that it's way longer, it seems reasonable to always truncate the message in favor of the prefix and date.
=> feat: allow automatic branch names up to GH's max supported length

src/actions/log_short.ts, src/lib/git-refs/branch_relations.ts, src/wrapper-classes/abstract_stack_builder.ts
=> chore: adding some debugs

src/actions/log_short.ts, src/commands/repo-commands/max_branch_length.ts, src/lib/git-refs/branch_relations.ts, src/wrapper-classes/abstract_stack_builder.ts
=> fix: max-branch-length command display

src/actions/log_short.ts, src/commands/repo-commands/max_branch_length.ts, src/lib/git-refs/branch_relations.ts, src/wrapper-classes/abstract_stack_builder.ts, src/wrapper-classes/stack.ts
```
↱ feat_ask_for_confirmation_before_submitt
↱ 04-08-feat_get_initial_version
↱ feat_get_push_stack_metadata_to_remote_o
↱ jg--04-13-fix_gt_ls_to_display_in_the_correct_direction
↱ jg--04-13-fix_max-branch-length_command_display
↱ jg--04-13-chore_adding_some_debugs
↱ main
```
=> fix: gt ls to display in the correct direction

src/actions/submit/submit.ts, src/lib/utils/is_empty_branch.ts, test/fast/actions/submit_action.test.ts
=> feat: ask for confirmation before submitting empty branch

src/actions/log_short.ts, src/commands/autocomplete.ts, src/commands/repo-commands/max_branch_length.ts, src/lib/git-refs/branch_relations.ts, src/wrapper-classes/abstract_stack_builder.ts, src/wrapper-classes/stack.ts
I will clean up this function at some point, but this is fine for now
=> feat: add autocomplete for branch delete

.CHANGELOG, package.json, src/actions/delete_branch.ts, src/actions/log_short.ts, src/commands/branch-commands/delete.ts, src/commands/repo-commands/ignored_branches.ts, test/fast/commands/branch/branch_delete.test.ts, test/lib/utils/fake_squash_and_merge.ts
=> bump: 0.17.9

src/commands/branch-commands/parent.ts, src/wrapper-classes/branch.ts
=> refactor: clean up branch.ts

src/actions/create_branch.ts, src/actions/fix.ts, src/actions/onto/stack_onto.ts, src/actions/submit/submit.ts, src/commands/branch-commands/parent.ts, src/wrapper-classes/branch.ts, src/wrapper-classes/metadata_ref.ts
=> feat(get): push stack metadata to remote on submit

src/actions/sync/sync.ts, src/commands/continue.ts, src/commands/repo-commands/repo_sync.ts
=> refactor: create folder for sync action components

src/actions/sync/sync.ts
=> fix: reorganize newlines in sync

src/actions/sync/pull.ts, src/actions/sync/sync.ts
=> refactor: move sync pull to own file

src/actions/fix_dangling_branches.ts, src/actions/sync/sync.ts, src/commands/repo-commands/fix.ts
=> refactor: clean up fixDanglingBranches

src/actions/clean_branches.ts, src/actions/fix_dangling_branches.ts, src/actions/sync/sync.ts, src/commands/continue.ts, src/commands/repo-commands/fix.ts
=> refactor: clean up deleteMergedBranches

src/actions/clean_branches.ts, src/actions/fix_dangling_branches.ts, src/actions/sync/resubmit_branches_with_new_bases.ts, src/actions/sync/sync.ts, src/commands/continue.ts, src/commands/repo-commands/fix.ts
=> refactor: move resubmitBranchesWithNewBases to new file

src/actions/clean_branches.ts, src/actions/create_branch.ts, src/actions/fix_dangling_branches.ts, src/actions/sync/resubmit_branches_with_new_bases.ts, src/actions/sync/sync.ts, src/commands/continue.ts, src/commands/repo-commands/fix.ts
=> fix: branch name max now reflects branch-metadata ref

src/actions/clean_branches.ts, src/actions/create_branch.ts, src/actions/fix_dangling_branches.ts, src/actions/sync/pull.ts, src/actions/sync/resubmit_branches_with_new_bases.ts, src/actions/sync/sync.ts, src/commands/continue.ts, src/commands/repo-commands/fix.ts
=> feat: sync pull now pulls from configured remote

src/actions/sync/pull.ts
=> refactor: separate pull --prune into prune and pull

src/actions/sync/pull.ts
=> refactor: split out fetch and merge

src/actions/sync/pull.ts
=> refactor: add specifics to pull

scripts/installation/develop.sh, src/actions/clean_branches.ts, src/actions/create_branch.ts, src/actions/fix_dangling_branches.ts, src/actions/sync/pull.ts, src/actions/sync/resubmit_branches_with_new_bases.ts, src/actions/sync/sync.ts, src/commands/branch-commands/pr-info.ts, src/commands/continue.ts, src/commands/repo-commands/fix.ts, src/lib/sync/pr_info.ts
=> fix: (and rename) branch sync command

src/actions/sync/pull.ts
=> feat: add remote branch metadata to fetch

package.json, src/actions/submit/submit.ts, src/wrapper-classes/branch.ts, yarn.lock
=> feat(cli): Send up revisions

src/actions/log_short.ts
=> fix: issue with ls where 'untracked' and 'off trunk' could be incorrectly shown

src/actions/submit/submit.ts
=> feat: stop allowing pushing to closed and merged branches from submit

src/actions/fix_dangling_branches.ts, src/actions/submit/submit.ts, src/commands/continue.ts, src/lib/telemetry/survey/survey.ts, src/lib/utils/assert_unreachable.ts, src/lib/utils/committer_date.ts
=> refactor: clean up assert_unreachable

.eslintrc, src/actions/fix_dangling_branches.ts, src/actions/submit/submit.ts, src/commands/continue.ts, src/lib/config/merge_conflict_callstack_config.ts, src/lib/config/message_config.ts, src/lib/config/user_config.ts, src/lib/telemetry/survey/survey.ts, src/lib/utils/assert_unreachable.ts, src/lib/utils/committer_date.ts, src/wrapper-classes/branch.ts, src/wrapper-classes/stack_node.ts
=> refactor: fix all unused vars lints

.eslintrc, src/actions/fix_dangling_branches.ts, src/actions/submit/pr_title.ts, src/actions/submit/submit.ts, src/commands/continue.ts, src/commands/stack-commands/test.ts, src/lib/config/merge_conflict_callstack_config.ts, src/lib/config/message_config.ts, src/lib/config/user_config.ts, src/lib/telemetry/survey/survey.ts, src/lib/telemetry/upgrade_prompt.ts, src/lib/utils/assert_unreachable.ts, src/lib/utils/committer_date.ts, src/wrapper-classes/branch.ts, src/wrapper-classes/stack_node.ts
=> refactor: fix all non-null assertions

src/actions/submit/submit.ts, src/lib/passthrough/index.ts, src/lib/telemetry/profile.ts, src/lib/telemetry/survey/survey.ts, src/lib/telemetry/tracer.ts, src/lib/utils/exec_sync.ts, src/lib/utils/ts_helpers.ts, src/wrapper-classes/stack.ts, src/wrapper-classes/stack_node.ts
=> refactor: fix unexpected anys

src/actions/submit/pr_body.ts, src/actions/submit/pr_title.ts, src/actions/submit/submit.ts, src/wrapper-classes/branch.ts, test/fast/actions/submit_action.test.ts
=> refactor: clean up submit

src/actions/submit/pr_body.ts, src/actions/submit/pr_title.ts, src/actions/submit/submit.ts, src/actions/submit/validate_branches.ts, src/wrapper-classes/branch.ts, test/fast/actions/submit_action.test.ts
=> refactor: move step 1 of submit to own file

src/actions/submit/prepare_branches.ts, src/actions/submit/submit.ts
=> refactor: move step 2 of submit to own file

src/actions/submit/pr_body.ts, src/actions/submit/pr_title.ts, src/actions/submit/prepare_branches.ts, src/actions/submit/submit.ts, src/actions/submit/validate_branches.ts, src/wrapper-classes/branch.ts, test/fast/actions/submit_action.test.ts
=> refactor: kill unused var in submit

src/actions/submit/push_branches.ts, src/actions/submit/submit.ts
=> refactor: move step 3 of submit to own file

src/actions/submit/submit.ts, src/actions/submit/submit_prs.ts
=> refactor: move step 4 of submit to own file

src/actions/submit/push_metadata.ts, src/actions/submit/submit.ts
=> refactor: move step 5 of submit to own file

src/actions/submit/prepare_branches.ts, src/actions/submit/push_branches.ts, src/actions/submit/push_metadata.ts, src/actions/submit/submit.ts, src/actions/submit/submit_prs.ts, src/lib/utils/exec_sync.ts
=> fix: some print formatting niceness

.CHANGELOG, package.json, src/actions/submit/prepare_branches.ts
Move from Promise.all(map) -> for await loop in order to fill in submit info synchronously.
=> fix(submit): small bug introduced in 0.17.10 and bump to 0.17.11

src/wrapper-classes/branch.ts
=> fix: submit bug related to branch names

src/lib/utils/git_repo.ts, test/fast/actions/remote_actions.test.ts, test/lib/scenes/clone_scene.ts
=> chore: add test for pushing branch to remote

test/fast/actions/remote_actions.test.ts
=> chore: add test for repo sync pull

src/actions/sync/prune_remote_branch_metadata.ts, src/actions/sync/sync.ts, src/commands/repo-commands/repo_sync.ts, src/lib/context/context.ts, src/lib/utils/git_repo.ts, test/fast/actions/remote_actions.test.ts, test/lib/scenes/abstract_scene.ts, test/lib/scenes/clone_scene.ts
=> feat: add step in sync to prune remote branch metadata

src/lib/utils/git_repo.ts, test/fast/actions/remote_actions.test.ts
=> chore: add test on pruning

src/actions/clean_branches.ts, src/actions/fix_dangling_branches.ts, src/actions/sync/prune_remote_branch_metadata.ts
=> feat: handle --no-interactive for sync

src/actions/sync/merge_downstack.ts, src/actions/sync/sync.ts, src/commands/downstack-commands/sync.ts, src/commands/repo-commands/repo_sync.ts, src/wrapper-classes/branch.ts, src/wrapper-classes/metadata_ref.ts, test/fast/actions/remote_actions.test.ts
=> feat: gt downstack sync

src/actions/branch_traversal.ts, src/actions/clean_branches.ts, src/actions/create_branch.ts, src/actions/edit/apply_stack_edit_pick.ts, src/actions/fix.ts, src/actions/interactive_branch_selection.ts, src/actions/onto/current_branch_onto.ts, src/actions/sync/pull.ts, src/actions/sync/sync.ts, src/commands/branch-commands/checkout.ts, src/commands/stack-commands/test.ts, src/lib/utils/checkout_branch.ts
=> refactor: clean up code related to switching branches

src/actions/branch_traversal.ts, src/actions/clean_branches.ts, src/actions/commit_amend.ts, src/actions/create_branch.ts, src/actions/edit/apply_stack_edit_pick.ts, src/actions/fix.ts, src/actions/interactive_branch_selection.ts, src/actions/onto/current_branch_onto.ts, src/actions/sync/pull.ts, src/actions/sync/sync.ts, src/commands/branch-commands/checkout.ts, src/commands/stack-commands/test.ts, src/lib/preconditions/index.ts, src/lib/utils/checkout_branch.ts, test/fast/commands/commit/amend.test.ts
=> fix: staged changes precondition

src/actions/branch_traversal.ts, src/actions/clean_branches.ts, src/actions/commit_amend.ts, src/actions/create_branch.ts, src/actions/edit/apply_stack_edit_pick.ts, src/actions/fix.ts, src/actions/interactive_branch_selection.ts, src/actions/onto/current_branch_onto.ts, src/actions/sync/pull.ts, src/actions/sync/sync.ts, src/commands/branch-commands/checkout.ts, src/commands/commit-commands/amend.ts, src/commands/stack-commands/test.ts, src/lib/preconditions/index.ts, src/lib/utils/checkout_branch.ts, test/fast/commands/commit/amend.test.ts
=> feat: --no-edit alias

src/actions/sync/merge_downstack.ts, src/actions/sync/sync.ts, test/fast/actions/remote_actions.test.ts
=> feat(dssync): add support for overwriting existing branches

src/actions/commit_amend.ts, src/actions/commit_create.ts, src/actions/fix.ts, src/lib/utils/indent_multiline_string.ts, src/wrapper-classes/stack.ts
=> refactor: clean up fix action

src/actions/onto/current_branch_onto.ts, src/actions/sync/sync.ts
=> refactor: use precondition helper function in a few more places

src/actions/onto/current_branch_onto.ts, src/actions/sync/sync.ts, src/lib/preconditions/index.ts, src/lib/utils/git_status_utils.ts, src/lib/utils/index.ts
=> refactor: clean up unused helper

src/actions/commit_amend.ts, src/actions/fix.ts, src/actions/onto/current_branch_onto.ts, src/actions/onto/stack_onto.ts, src/actions/sync/sync.ts, src/lib/preconditions/index.ts, src/lib/utils/git_status_utils.ts, src/lib/utils/index.ts, src/wrapper-classes/branch.ts
=> refactor: replace setMetaPrevRef with savePrevRef

src/actions/submit/pr_draft.ts, src/actions/submit/submit.ts, src/actions/sync/resubmit_branches_with_new_bases.ts, src/commands/branch-commands/submit.ts, src/commands/downstack-commands/submit.ts, src/commands/shared-commands/submit.ts, src/commands/stack-commands/submit.ts, src/commands/upstack-commands/submit.ts
=> feat: add option to confirm submit commands before pushing

src/actions/branch_traversal.ts, src/actions/clean_branches.ts, src/actions/edit/apply_stack_edit_pick.ts, src/actions/edit/edit_downstack.ts, src/actions/fix.ts, src/actions/onto/current_branch_onto.ts, src/actions/onto/stack_onto.ts, src/actions/submit/submit_prs.ts, src/commands/continue.ts, src/commands/upstack-commands/onto.ts, src/lib/sync/pr_info.ts, src/wrapper-classes/branch.ts, test/fast/actions/submit_action.test.ts, test/fast/commands/branch/branch_create.test.ts
=> refactor: remove unnecessary awaits

src/actions/branch_traversal.ts, src/actions/clean_branches.ts, src/actions/commit_amend.ts, src/actions/edit/apply_stack_edit_pick.ts, src/actions/edit/edit_downstack.ts, src/actions/fix.ts, src/actions/onto/current_branch_onto.ts, src/actions/onto/stack_onto.ts, src/actions/submit/submit_prs.ts, src/actions/sync/sync.ts, src/commands/continue.ts, src/commands/upstack-commands/onto.ts, src/lib/preconditions/index.ts, src/lib/sync/pr_info.ts, src/lib/utils/git_status_utils.ts, src/lib/utils/index.ts, src/wrapper-classes/branch.ts, test/fast/actions/submit_action.test.ts, test/fast/commands/branch/branch_create.test.ts
=> refactor: clean up setParentBranch API

src/actions/branch_traversal.ts, src/actions/clean_branches.ts, src/actions/commit_amend.ts, src/actions/edit/apply_stack_edit_pick.ts, src/actions/edit/edit_downstack.ts, src/actions/fix.ts, src/actions/onto/current_branch_onto.ts, src/actions/onto/stack_onto.ts, src/actions/submit/submit_prs.ts, src/actions/sync/sync.ts, src/commands/continue.ts, src/commands/upstack-commands/onto.ts, src/lib/preconditions/index.ts, src/lib/sync/pr_info.ts, src/lib/utils/git_status_utils.ts, src/lib/utils/index.ts, src/wrapper-classes/branch.ts, test/fast/actions/submit_action.test.ts, test/fast/commands/branch/branch_create.test.ts
=> refactor: kill a couple unused Branch methods

src/actions/branch_traversal.ts, src/actions/clean_branches.ts, src/actions/commit_amend.ts, src/actions/edit/apply_stack_edit_pick.ts, src/actions/edit/edit_downstack.ts, src/actions/fix.ts, src/actions/onto/current_branch_onto.ts, src/actions/onto/stack_onto.ts, src/actions/submit/submit_prs.ts, src/actions/sync/sync.ts, src/commands/continue.ts, src/commands/upstack-commands/onto.ts, src/lib/preconditions/index.ts, src/lib/sync/pr_info.ts, src/lib/utils/git_status_utils.ts, src/lib/utils/index.ts, src/wrapper-classes/branch.ts, test/fast/actions/submit_action.test.ts, test/fast/commands/branch/branch_create.test.ts
=> fix: clear parent sha when parent metadata is cleared

src/actions/branch_traversal.ts, src/actions/clean_branches.ts, src/actions/commit_amend.ts, src/actions/edit/apply_stack_edit_pick.ts, src/actions/edit/edit_downstack.ts, src/actions/fix.ts, src/actions/onto/current_branch_onto.ts, src/actions/onto/stack_onto.ts, src/actions/submit/submit_prs.ts, src/actions/submit/validate_branches.ts, src/actions/sync/sync.ts, src/actions/validate.ts, src/commands/continue.ts, src/commands/upstack-commands/onto.ts, src/lib/preconditions/index.ts, src/lib/sync/pr_info.ts, src/lib/utils/git_status_utils.ts, src/lib/utils/index.ts, src/wrapper-classes/abstract_stack_builder.ts, src/wrapper-classes/branch.ts, src/wrapper-classes/stack.ts, test/fast/actions/submit_action.test.ts, test/fast/actions/validate_action.test.ts, test/fast/commands/branch/branch_create.test.ts
=> refactor: clean up stack validation code

src/actions/branch_traversal.ts, src/actions/clean_branches.ts, src/actions/commit_amend.ts, src/actions/create_branch.ts, src/actions/edit/apply_stack_edit_pick.ts, src/actions/edit/edit_downstack.ts, src/actions/fix.ts, src/actions/onto/current_branch_onto.ts, src/actions/onto/stack_onto.ts, src/actions/submit/submit_prs.ts, src/actions/submit/validate_branches.ts, src/actions/sync/sync.ts, src/actions/validate.ts, src/commands/branch-commands/create.ts, src/commands/continue.ts, src/commands/upstack-commands/onto.ts, src/lib/preconditions/index.ts, src/lib/sync/pr_info.ts, src/lib/utils/git_status_utils.ts, src/lib/utils/index.ts, src/wrapper-classes/abstract_stack_builder.ts, src/wrapper-classes/branch.ts, src/wrapper-classes/stack.ts, test/fast/actions/submit_action.test.ts, test/fast/actions/validate_action.test.ts, test/fast/commands/branch/branch_create.test.ts, test/fast/commands/branch/children.test.ts
=> feat: add --insert option for branch create

src/actions/clean_branches.ts, src/actions/create_branch.ts, src/actions/onto/stack_onto.ts
=> fix: some logging around upstack onto

src/actions/interactive_branch_selection.ts, src/commands/branch-commands/checkout.ts, src/commands/upstack-commands/onto.ts, src/wrapper-classes/branch.ts, src/wrapper-classes/stack.ts
=> feat: add interactive selection for upstack onto

src/actions/interactive_branch_selection.ts, src/commands/branch-commands/checkout.ts, src/commands/upstack-commands/onto.ts, src/wrapper-classes/branch.ts, src/wrapper-classes/stack.ts
=> refactor: clean up (slightly) memoization logic in Branch.ts (there is still a lot more to do here)

src/actions/interactive_branch_selection.ts, src/commands/branch-commands/checkout.ts, src/commands/upstack-commands/onto.ts, src/lib/git-refs/branch_relations.ts, src/wrapper-classes/branch.ts, src/wrapper-classes/stack.ts
=> refactor: clean up memoization logic some more

src/lib/config/cache.ts, src/lib/git-refs/branch_relations.ts, src/wrapper-classes/branch.ts
=> refactor: move all memoization logic to cache

src/actions/interactive_branch_selection.ts, src/actions/onto/stack_onto.ts, src/actions/validate.ts, src/commands/branch-commands/checkout.ts, src/commands/upstack-commands/onto.ts, src/lib/config/cache.ts, src/lib/git-refs/branch_relations.ts, src/wrapper-classes/branch.ts, src/wrapper-classes/stack.ts
=> fix: use memoization for validation

src/actions/fix.ts, src/actions/interactive_branch_selection.ts, src/actions/onto/stack_onto.ts, src/actions/validate.ts, src/commands/branch-commands/checkout.ts, src/commands/stack-commands/fix.ts, src/commands/upstack-commands/fix.ts, src/commands/upstack-commands/onto.ts, src/lib/config/cache.ts, src/lib/git-refs/branch_relations.ts, src/wrapper-classes/branch.ts, src/wrapper-classes/stack.ts
=> refactor: use common TScope enum in fix

src/actions/fix.ts, src/actions/validate.ts
=> refactor: clean up some pre-fix validation code

src/actions/fix.ts, src/commands/stack-commands/fix.ts, src/commands/upstack-commands/fix.ts
=> refactor: clean up more fix stuff

src/actions/fix.ts, src/actions/validate.ts
=> feat: update parentrevision in more places

src/actions/edit_branch.ts, src/actions/fix.ts, src/actions/validate.ts, src/commands/branch-commands/edit.ts
=> feat: gt branch edit

src/actions/edit_branch.ts, src/actions/fix.ts, src/actions/show_branch.ts, src/actions/validate.ts, src/commands/branch-commands/edit.ts, src/commands/branch-commands/show.ts
=> feat: gt branch show

src/actions/show_branch.ts, src/commands/branch-commands/show.ts
=> feat: patch opt for branch show

src/actions/edit/edit_downstack.ts, src/actions/edit_branch.ts, src/actions/fix.ts, src/actions/show_branch.ts, src/actions/validate.ts, src/commands/branch-commands/edit.ts, src/commands/branch-commands/show.ts, src/lib/utils/perform_in_tmp_dir.ts, test/fast/commands/downstack/edit.test.ts
=> refactor: kill unneeded awaits

src/actions/edit/parse_stack_edit_file.ts, src/actions/edit/stack_edits.ts
=> feat: improve stack edit parsing

src/actions/edit/apply_stack_edit_pick.ts, src/actions/edit/create_stack_edit_file.ts, src/actions/edit/edit_downstack.ts, src/actions/edit/parse_stack_edit_file.ts, src/actions/edit/stack_edits.ts, src/commands/continue.ts
=> refactor: clean up stack edit rebasing

src/actions/fix.ts, src/actions/onto/stack_onto.ts, src/lib/utils/rebase_onto.ts
=> fix: unify rebase code

src/actions/interactive_branch_selection.ts, src/lib/utils/checkout_branch.ts
=> fix: interactive branch selection if not on a graphite branch

src/actions/delete_branch.ts, src/actions/interactive_branch_selection.ts, src/lib/utils/checkout_branch.ts
=> fix: only delete metadata if delete succeeds

src/actions/clean_branches.ts, src/actions/delete_branch.ts, src/commands/branch-commands/delete.ts
=> feat: support deleting current branch

src/commands/continue.ts
=> feat: gt continue -a

src/actions/sync/merge_downstack.ts, src/commands/continue.ts, src/commands/downstack-commands/sync.ts
=> feat: hide downstack sync behind the multiplayer config

src/actions/submit/push_metadata.ts, src/actions/sync/merge_downstack.ts, src/actions/sync/prune_remote_branch_metadata.ts, src/actions/sync/pull.ts, src/commands/downstack-commands/sync.ts, src/commands/user-commands/experimental.ts, src/lib/config/user_config.ts, test/lib/scenes/clone_scene.ts
=> feat: add gt user experimental command to toggle multiplayer config; shore up some copy around the gating

.CHANGELOG, package.json, src/actions/submit/push_metadata.ts, src/actions/sync/merge_downstack.ts, src/actions/sync/prune_remote_branch_metadata.ts, src/actions/sync/pull.ts, src/commands/continue.ts, src/commands/downstack-commands/sync.ts, src/commands/user-commands/experimental.ts, src/lib/config/user_config.ts, test/lib/scenes/clone_scene.ts
=> chore(bump): 0.18.0

src/lib/utils/trunk.ts
=> fix: don't try to infer trunk inline

src/actions/submit/submit_prs.ts, src/lib/utils/trunk.ts, src/wrapper-classes/metadata_ref.ts
=> feat: add body to PR info and update all fields on submit

src/actions/print_stack.ts, src/actions/submit/pr_body.ts, src/actions/submit/pr_title.ts, src/actions/submit/prepare_branches.ts, src/actions/submit/submit_prs.ts, src/lib/utils/trunk.ts, src/wrapper-classes/branch.ts, src/wrapper-classes/metadata_ref.ts
=> refactor: kill priorsubmitinfo in favor of prinfo

src/actions/print_stack.ts, src/actions/submit/pr_body.ts, src/actions/submit/pr_title.ts, src/actions/submit/prepare_branches.ts, src/actions/submit/submit_prs.ts, src/lib/utils/signpost_deprecated_commands.ts, src/lib/utils/trunk.ts, src/wrapper-classes/branch.ts, src/wrapper-classes/metadata_ref.ts
=> feat: kill stacks warning

src/actions/submit/prepare_branches.ts
=> fix: don't print submit info header in non-interactive mode

src/actions/create_branch.ts, src/commands/user-commands/branch_prefix.ts, src/lib/utils/branch_name.ts
=> refactor: branch name/prefix calculation

src/commands/user-commands/branch_date.ts, src/lib/config/user_config.ts, src/lib/utils/branch_name.ts
=> feat: enable toggling branch date

src/commands/user-commands/branch_replacement.ts, src/lib/config/user_config.ts, src/lib/utils/branch_name.ts
=> feat: enable changing replacement character

src/actions/create_branch.ts, src/lib/utils/checkout_branch.ts
=> refactor: use checkout_branch lib for create_branch action

src/actions/sync/merge_downstack.ts
=> fix(sync): abort behavior

src/actions/clean_branches.ts, src/actions/sync/sync.ts, src/commands/continue.ts, src/commands/repo-commands/fix.ts, src/lib/utils/git_repo.ts, src/wrapper-classes/metadata_ref.ts, test/fast/commands/repo/sync.test.ts
=> feat: also clean CLOSED branches in repo sync

src/actions/clean_branches.ts, src/actions/sync/sync.ts, src/commands/continue.ts, src/commands/repo-commands/fix.ts, src/lib/config/compose_config.ts, src/lib/utils/git_repo.ts, src/wrapper-classes/metadata_ref.ts, test/fast/commands/repo/sync.test.ts
=> fix(security): config file permissions 644 -> 600

src/actions/clean_branches.ts, src/actions/sync/sync.ts, src/commands/continue.ts, src/commands/repo-commands/fix.ts, src/lib/config/compose_config.ts, src/lib/config/repo_config.ts, src/lib/utils/git_repo.ts, src/wrapper-classes/metadata_ref.ts, test/fast/commands/repo/sync.test.ts, test/fast/commands/repo_config/repo_config.test.ts
=> fix: owner/name inference

.CHANGELOG, package.json, src/actions/clean_branches.ts, src/actions/sync/sync.ts, src/commands/continue.ts, src/commands/repo-commands/fix.ts, src/lib/config/compose_config.ts, src/lib/config/repo_config.ts, src/lib/utils/git_repo.ts, src/wrapper-classes/metadata_ref.ts, test/fast/commands/repo/sync.test.ts, test/fast/commands/repo_config/repo_config.test.ts
=> chore(bump): 0.18.1

src/commands/user-commands/branch_prefix.ts
=> feat: allow turning off branch prefix

.CHANGELOG, package.json, src/actions/commit_amend.ts, src/actions/commit_create.ts, src/actions/edit_branch.ts
=> chore(bump): 0.18.2 and a small temporary fix

src/actions/submit/prepare_branches.ts
=> fix: save  title if canceled during body edit

src/actions/sync/pull.ts, src/wrapper-classes/branch.ts, src/wrapper-classes/metadata_ref.ts, test/fast/actions/remote_actions.test.ts
=> feat: remove fetching remote metadata ref

package.json, src/actions/sync/get_downstack_dependencies.ts, src/commands/downstack-commands/sync.ts, yarn.lock
=> feat: stub for downstack sync, call new endpoint

src/actions/sync/pull.ts, src/actions/sync/sync.ts, src/lib/utils/get_remote_branch_names.ts, test/fast/actions/remote_actions.test.ts
=> feat: specify which branches to fetch on sync

src/actions/sync/sync.ts, src/commands/downstack-commands/sync.ts, src/commands/repo-commands/repo_sync.ts
=> feat: sync requested stack on ds sync

src/actions/sync/get_downstack_dependencies.ts, src/commands/downstack-commands/sync.ts
=> feat: add validation on downstack dependency response

src/actions/sync/merge_downstack.ts, src/actions/sync/sync.ts, src/lib/utils/copy_from_remote.ts
=> feat: copy downstack from remote

src/actions/sync/merge_downstack.ts, src/commands/branch-commands/pr-info.ts, src/lib/sync/pr_info.ts
=> feat: sync pr info for synced downstack

.CHANGELOG, package.json
=> chore(bump): 0.18.3

src/actions/init.ts, src/actions/sync/sync.ts, src/lib/preconditions.ts, src/lib/utils/branch_exists.ts, src/lib/utils/trunk.ts, src/wrapper-classes/branch.ts, test/fast/commands/branch/branch_delete.test.ts
=> refactor: move branch existence call out of branch class

src/actions/branch_traversal.ts, src/actions/init.ts, src/actions/onto/stack_onto.ts, src/actions/submit/submit_prs.ts, src/actions/sync/sync.ts, src/actions/validate.ts, src/commands/continue.ts, src/lib/preconditions.ts, src/lib/sync/pr_info.ts, src/lib/utils/branch_exists.ts, src/lib/utils/trunk.ts, src/wrapper-classes/branch.ts, test/fast/actions/submit_action.test.ts, test/fast/commands/branch/branch_create.test.ts, test/fast/commands/branch/branch_delete.test.ts
=> refactor: use branchExists for branchWithName

src/actions/branch_traversal.ts, src/actions/commit_amend.ts, src/actions/commit_create.ts, src/actions/delete_branch.ts, src/actions/init.ts, src/actions/interactive_branch_selection.ts, src/actions/onto/stack_onto.ts, src/actions/print_stack.ts, src/actions/submit/submit_prs.ts, src/actions/sync/sync.ts, src/actions/validate.ts, src/commands/branch-commands/pr-info.ts, src/commands/continue.ts, src/commands/log-commands/default.ts, src/lib/preconditions.ts, src/lib/sync/pr_info.ts, src/lib/utils/branch_exists.ts, src/lib/utils/current_branch_name.ts, src/lib/utils/trunk.ts, src/wrapper-classes/branch.ts, test/fast/actions/submit_action.test.ts, test/fast/commands/branch/branch_create.test.ts, test/fast/commands/branch/branch_delete.test.ts
=> refactor pull out currentBranchName logic

src/actions/branch_traversal.ts, src/actions/commit_amend.ts, src/actions/commit_create.ts, src/actions/delete_branch.ts, src/actions/fix_dangling_branches.ts, src/actions/init.ts, src/actions/interactive_branch_selection.ts, src/actions/onto/stack_onto.ts, src/actions/print_stack.ts, src/actions/submit/submit_prs.ts, src/actions/sync/resubmit_branches_with_new_bases.ts, src/actions/sync/sync.ts, src/actions/validate.ts, src/commands/autocomplete.ts, src/commands/branch-commands/pr-info.ts, src/commands/continue.ts, src/commands/log-commands/default.ts, src/lib/preconditions.ts, src/lib/sync/pr_info.ts, src/lib/utils/branch_exists.ts, src/lib/utils/committer_date.ts, src/lib/utils/current_branch_name.ts, src/lib/utils/sorted_branch_names.ts, src/lib/utils/trunk.ts, src/wrapper-classes/branch.ts, test/fast/actions/submit_action.test.ts, test/fast/commands/branch/branch_create.test.ts, test/fast/commands/branch/branch_delete.test.ts, test/fast/commands/branch/children.test.ts
=> refactor: clean up allBranches logic

src/actions/fix.ts
=> refactor: clean up fix

src/actions/fix.ts, src/actions/validate.ts
=> refactor: clean up CBP call in validation

.CHANGELOG, package.json, src/commands/downstack-commands/sync.ts
=> chore(bump): 0.18.4, fix dssync experimental requirement

src/actions/interactive_branch_selection.ts
=> fix: interactive branch selection default

src/lib/utils/branch_name.ts
=> feat: support dot and slash in branch names

.CHANGELOG, package.json
=> chore(bump): 0.18.5

src/commands/branch-commands/rename.ts
=> feat: guardrail for rename

src/commands/branch-commands/rename.ts, src/lib/utils/branch_name.ts
=> feat: use branch name allowlist in rename

.CHANGELOG, package.json, src/commands/branch-commands/rename.ts, src/lib/utils/branch_name.ts
=> chore(bump): 0.18.6

src/commands/repo-commands/ignored_branches.ts, src/commands/stack-commands/test.ts, src/lib/config/repo_config.ts, src/lib/config/repo_root_path.ts, src/lib/debugContext.ts, src/lib/git/committer_date.ts, src/lib/git/current_branch_name.ts, src/lib/git/detect_unsubmitted_changes.ts, src/lib/git/get_remote_branch_names.ts, src/lib/git/merge_base.ts, src/lib/git/merge_conflict_help.ts, src/lib/preconditions.ts, src/lib/utils/default_editor.ts, src/lib/utils/exec_sync.ts, src/wrapper-classes/branch.ts, src/wrapper-classes/commit.ts
=> refactor: clean up some execsync stuff

scripts/installation/install_nightly.sh, scripts/installation/uninstall.sh
=> chore: remove refs to nightly cli build

scripts/deploy/deploy.ts, src/actions/clean_branches.ts, src/actions/create_branch.ts, src/actions/delete_branch.ts, src/lib/debugContext.ts, src/lib/git/deleteBranch.ts
=> refactor cleanup git calls for branch deletion

scripts/deploy/deploy.ts, src/actions/clean_branches.ts, src/actions/create_branch.ts, src/actions/delete_branch.ts, src/actions/submit/pr_body.ts, src/commands/continue.ts, src/commands/demo.ts, src/commands/dev-commands/stack.ts, src/commands/log-commands/long.ts, src/lib/debugContext.ts, src/lib/git/branch_exists.ts, src/lib/git/deleteBranch.ts, src/lib/git/detect_staged_changes.ts, src/lib/git/git_status_utils.ts, src/lib/git/is_empty_branch.ts, src/lib/git/merge_conflict_help.ts, src/lib/git/rebase_in_progress.ts, src/lib/git/sorted_branch_names.ts, src/lib/telemetry/context.ts, src/lib/telemetry/profile.ts, src/lib/utils/git_repo.ts, src/lib/utils/trunk.ts, src/wrapper-classes/branch.ts, src/wrapper-classes/commit.ts, src/wrapper-classes/metadata_ref.ts, test/fast/commands/branch/branch_delete.test.ts
=> refactor: clean up a git status call

scripts/installation/uninstall.sh
=> fix: uninstall script

src/lib/config/repo_root_path.ts, src/lib/utils/trunk.ts
=> refactor: clean up findRemoteOriginBranch function

src/lib/config/repo_root_path.ts
=> fix: worktree support

src/lib/utils/trunk.ts
=> refactor: cleanup a direct git config access

src/actions/submit/push_branch.ts, src/lib/config/repo_config.ts, src/lib/config/repo_root_path.ts, src/lib/preconditions.ts, src/lib/utils/trunk.ts
=> chore: kill unnecessary return Buffer(0)s

scripts/demo/abstract_demo.ts, scripts/demo/full_demo.ts, scripts/demo/index.ts
=> chore: fix lints in demo script

scripts/installation/install_stable.sh, scripts/installation/uninstall.sh
=> chore: update intall scripts to assume npm over brew

src/lib/utils/spawn.ts
=> fix: remove unnecessary /usr/bin/env

src/actions/branch_traversal.ts, src/actions/commit_amend.ts, src/actions/commit_create.ts, src/actions/create_branch.ts, src/actions/edit/apply_stack_edit.ts, src/actions/edit/edit_downstack.ts, src/actions/edit_branch.ts, src/actions/fix.ts, src/actions/log_short.ts, src/actions/onto/current_branch_onto.ts, src/actions/show_branch.ts, src/actions/submit/validate_branches.ts, src/actions/sync/pull.ts, src/actions/sync/sync.ts, src/actions/validate.ts, src/commands/branch-commands/children.ts, src/commands/branch-commands/parent.ts, src/commands/branch-commands/pr-info.ts, src/commands/branch-commands/rename.ts, src/commands/stack-commands/test.ts, src/commands/upstack-commands/onto.ts, src/lib/debugContext.ts, src/lib/errors.ts, src/lib/git-refs/branch_ref.ts, src/lib/git-refs/branch_relations.ts, src/lib/preconditions.ts, src/wrapper-classes/branch.ts, src/wrapper-classes/git_stack_builder.ts, test/fast/wrapper-classes/branch.test.ts
=> chore: remove uneeded contexts

src/actions/fix.ts, src/actions/log_short.ts, src/commands/shared-commands/fix.ts, src/commands/stack-commands/fix.ts, src/commands/upstack-commands/fix.ts, test/fast/actions/validate_action.test.ts, test/fast/commands/repo/fix_continue.test.ts, test/fast/commands/repo/sync_continue.test.ts, test/fast/commands/stack/fix.test.ts, test/fast/commands/stack/fix_continue.test.ts, test/fast/commands/upstack/fix.test.ts, test/fast/commands/upstack/onto_continue.test.ts
=> feat: remove sf --regen

src/actions/commit_amend.ts, src/actions/commit_create.ts, src/actions/edit_branch.ts, src/actions/fix.ts, src/actions/log_short.ts, src/commands/branch-commands/edit.ts, src/commands/commit-commands/amend.ts, src/commands/commit-commands/create.ts, src/commands/shared-commands/fix.ts, src/commands/stack-commands/fix.ts, src/commands/upstack-commands/fix.ts, test/fast/actions/validate_action.test.ts, test/fast/commands/repo/fix_continue.test.ts, test/fast/commands/repo/sync_continue.test.ts, test/fast/commands/stack/fix.test.ts, test/fast/commands/stack/fix_continue.test.ts, test/fast/commands/upstack/fix.test.ts, test/fast/commands/upstack/onto_continue.test.ts
=> refactor: kill all the awaits that lets us kill

src/actions/fix.ts, src/actions/onto/stack_onto.ts, src/commands/continue.ts, src/commands/stack-commands/fix.ts, src/commands/upstack-commands/fix.ts
=> refactor: clean up fix calls

src/actions/commit_amend.ts, src/actions/commit_create.ts, src/actions/edit_branch.ts, src/actions/fix.ts
=> fix: make fix behavior even more consistent

src/commands/dev-commands/migration.ts, src/lib/validation/validate.ts
=> feat: stub new validation + dev command for testing it

src/lib/validation/validate.ts
=> feat: get all metadata refs

src/lib/validation/validate.ts
=> feat: validation algorithm

src/actions/create_branch.ts, src/actions/fix.ts, src/actions/onto/stack_onto.ts, src/actions/submit/prepare_branches.ts, src/actions/sync/merge_downstack.ts, src/actions/validate.ts, src/lib/git/get_branch_revision.ts, src/lib/git/rebase.ts, src/lib/validation/cache.ts, src/wrapper-classes/branch.ts
=> refactor: clean up getting current revision of a branch

src/actions/sync/sync.ts, src/commands/downstack-commands/sync.ts, src/commands/repo-commands/repo_sync.ts, src/wrapper-classes/metadata_ref.ts, test/fast/commands/repo/sync.test.ts
=> feat: kill dangling branch step in sync

src/lib/validation/cache.ts
=> feat: keep track of children for invalid branches

src/actions/delete_branch.ts, src/commands/log-commands/default.ts, src/lib/git/current_branch_name.ts, src/lib/git/get_branch_revision.ts, src/lib/validation/cache.ts, src/wrapper-classes/branch.ts
=> refactor: clean up currentBranchName

src/commands/feedback-commands/debug_context.ts, src/commands/feedback-commands/default.ts, src/lib/debug_context.ts
=> fix: debugContext recreate for parentBranchRevision

src/actions/branch_traversal.ts, src/commands/feedback-commands/debug_context.ts, src/commands/feedback-commands/default.ts, src/lib/context.ts, src/lib/debug_context.ts, src/lib/telemetry/profile.ts, src/lib/validation/cache.ts
=> refactor: migrate branch navigation commands to use new cache layer

src/lib/validation/cache.ts
=> refactor: internal cache map->record

src/actions/interactive_branch_selection.ts, src/commands/branch-commands/checkout.ts, src/lib/telemetry/profile.ts, src/lib/validation/cache.ts, src/wrapper-classes/stack.ts
=> refactor: move checkout and interactive branch selection to cache

src/actions/clean_branches.ts, src/actions/create_branch.ts, src/actions/delete_branch.ts, src/actions/edit/apply_stack_edit.ts, src/actions/edit/edit_downstack.ts, src/actions/fix.ts, src/actions/interactive_branch_selection.ts, src/actions/onto/current_branch_onto.ts, src/actions/sync/pull.ts, src/actions/sync/sync.ts, src/commands/branch-commands/checkout.ts, src/commands/stack-commands/test.ts, src/lib/git/checkout_branch.ts, src/lib/telemetry/profile.ts, src/lib/validation/cache.ts, src/wrapper-classes/stack.ts
=> refactor: kill quiet option on checkout call

src/commands/dev-commands/migration.ts, src/lib/state/cache.ts, src/lib/telemetry/profile.ts
=> chore: make the cache debugging command useful

src/actions/submit/submit_prs.ts, src/lib/config/compose_config.ts, src/lib/state/cache.ts, src/lib/telemetry/post_traces.ts, src/lib/telemetry/tracer.ts, src/lib/utils/cute_string.ts, src/wrapper-classes/metadata_ref.ts, test/lib/scenes/abstract_scene.ts, test/lib/scenes/clone_scene.ts, test/lib/scenes/public_repo_scene.ts
=> refactor: add helper fn for stringify

src/actions/restack.ts, src/commands/branch-commands/restack.ts, src/commands/continue.ts, src/lib/errors.ts, src/lib/git/rebase.ts, src/lib/state/cache.ts, src/lib/telemetry/profile.ts, test/fast/commands/commit/amend_continue.test.ts, test/fast/commands/commit/create_continue.test.ts, test/fast/commands/downstack/edit.test.ts, test/fast/commands/repo/fix_continue.test.ts, test/fast/commands/repo/sync_continue.test.ts, test/fast/commands/stack/fix_continue.test.ts, test/fast/commands/upstack/onto_continue.test.ts
=> feat: gt branch restack

src/lib/git/merge_conflict_help.ts, src/lib/telemetry/profile.ts
=> feat: custom status for merge conflicts

src/lib/state/cache.ts
=> fix: only return valid children from cache interface

src/lib/state/cache.ts
=> refactor: move fixed status to a function instead of cached state

src/actions/restack.ts, src/commands/continue.ts, src/commands/upstack-commands/restack.ts, src/lib/config/merge_conflict_callstack_config.ts, src/lib/context.ts, src/lib/git/rebase.ts, src/lib/state/cache.ts
=> feat: upstack restack

src/actions/restack.ts, src/commands/downstack-commands/restack.ts, src/commands/stack-commands/restack.ts, src/lib/state/cache.ts
=> feat: add stack and downstack restack

src/actions/clean_branches.ts, src/actions/create_branch.ts, src/actions/current_branch_onto.ts, src/actions/edit/apply_stack_edit.ts, src/commands/upstack-commands/onto.ts
=> refactor: move a file

src/actions/clean_branches.ts, src/actions/create_branch.ts, src/actions/current_branch_onto.ts, src/actions/edit/apply_stack_edit.ts, src/actions/test.ts, src/commands/stack-commands/test.ts, src/commands/upstack-commands/onto.ts
=> refactor move stack test to new infra and clean up a little

src/actions/test.ts, src/commands/downstack-commands/test.ts, src/commands/upstack-commands/test.ts
=> feat: add downstack test and upstack test

src/actions/clean_branches.ts, src/actions/delete_branch.ts, src/actions/test.ts, src/commands/downstack-commands/test.ts, src/commands/upstack-commands/test.ts, src/lib/state/cache.ts
=> refactor: logic to determine whether a branch should be deleted

src/actions/clean_branches.ts, src/actions/create_branch.ts, src/actions/delete_branch.ts, src/actions/edit/apply_stack_edit.ts, src/actions/edit/edit_downstack.ts, src/actions/sync/pull.ts, src/actions/sync/sync.ts, src/lib/debug_context.ts, src/lib/git/checkout_branch.ts, src/lib/state/cache.ts
=> refactor: rename function

src/actions/delete_branch.ts, src/lib/state/cache.ts, src/wrapper-classes/metadata_ref.ts
=> refactor: move delete to cache

src/commands/branch-commands/rename.ts, src/lib/config/merge_conflict_callstack_config.ts, src/lib/config/survey_config.ts, src/lib/config/user_config.ts, src/lib/context.ts, src/lib/debug_context.ts, src/lib/state/cache.ts, src/lib/utils/git_repo.ts, src/wrapper-classes/branch.ts, src/wrapper-classes/metadata_ref.ts, test/fast/commands/branch/branch_delete.test.ts
=> refactor: move metadataref away from OOP

src/lib/git/rebase.ts, src/wrapper-classes/branch.ts, src/wrapper-classes/metadata_ref.ts
=> chore: kill prevRef

src/actions/rename_branch.ts, src/commands/branch-commands/rename.ts, src/lib/git/branch_move.ts, src/lib/git/rebase.ts, src/lib/state/cache.ts, src/wrapper-classes/branch.ts, src/wrapper-classes/metadata_ref.ts
=> refactor: move rename to cache

src/actions/create_branch.ts, src/lib/config/merge_conflict_callstack_config.ts, src/lib/git/rebase.ts, src/lib/state/cache.ts, test/fast/commands/branch/branch_create.test.ts
=> refactor: move create branch to cache

package.json, src/actions/scope.ts, src/commands/demo.ts, src/commands/feedback-commands/default.ts, src/commands/repo-commands/pr_templates.ts, src/commands/repo-commands/repo_trunk.ts, src/lib/telemetry/sigint_handler.ts, src/lib/utils/exec_sync.ts, src/lib/utils/pr_templates.ts, test/lib/scenes/abstract_scene.ts, test/lib/scenes/public_repo_scene.ts, yarn.lock
=> refactor: clean up random stuff

.husky/commit-msg, .husky/pre-commit, package.json, yarn.lock
=> chore: precommit -> husky

src/lib/state/metadata_ref.ts, src/lib/utils/git_repo.ts, src/wrapper-classes/branch.ts
=> refactor: clean up metadataref read type

src/lib/git/commit_range.ts, src/lib/git/commit_tree.ts, src/lib/git/get_remote_branch_names.ts, src/lib/git/merge_conflict_help.ts, src/lib/git/sorted_branch_names.ts, src/lib/state/cache.ts, src/lib/state/metadata_ref.ts, src/lib/utils/exec_sync.ts, src/lib/utils/git_repo.ts
=> feat: autofix parentbranchrevision during cache load

src/wrapper-classes/branch.ts
=> refactor: kill more Branch class stuff

src/actions/clean_branches.ts, src/actions/delete_branch.ts, src/actions/edit/edit_downstack.ts, src/actions/edit_branch.ts, src/actions/restack.ts, src/actions/submit/validate_branches.ts, src/actions/sync/sync.ts, src/actions/test.ts, src/commands/continue.ts, src/lib/state/cache.ts
=> refactor: cleanBranchAction to use cache

src/index.ts
=> chore: clean up duplicated globalArgs middleware

src/actions/sync/sync.ts
=> refactor: remove a Branch call from sync

src/actions/sync/merge_downstack.ts, src/actions/sync/pull.ts, src/actions/sync/sync.ts, src/commands/downstack-commands/sync.ts, src/commands/repo-commands/repo_sync.ts, test/fast/actions/remote_actions.test.ts
=> refactor: first pass at sync

src/actions/clean_branches.ts, src/actions/submit/validate_branches.ts, src/actions/sync/merge_downstack.ts, src/actions/sync/sync.ts, src/lib/requests/fetch_pr_info.ts, src/lib/sync/pr_info.ts
=> refactor: pull out dependency on cache from API call

src/lib/engine/cache.ts
=> feat: read all branches into cache

src/lib/utils/splog.ts
=> chore: debug text gray

src/lib/engine/build_cache.ts, src/lib/engine/cache.ts, src/lib/engine/cached_meta.ts
=> refactor: start splitting up cache.ts

src/lib/engine/cache.ts, src/lib/engine/cached_meta.ts
=> refactor: clean up cache.ts a little more

src/actions/sync/merge_downstack.ts, src/lib/preconditions.ts, src/lib/utils/trunk.ts, src/wrapper-classes/branch.ts
=> refactor: kill almost all of branch.ts

src/actions/init.ts, src/lib/engine/cache.ts, src/lib/engine/parse_branches.ts, test/fast/commands/repo/trunk.test.ts
=> feat: load cache on repo init

src/actions/submit/prepare_branches.ts, src/actions/submit/submit_action.ts, src/actions/submit/submit_prs.ts
=> refactor: clean up some typing stuff for submit

src/actions/commit_amend.ts, src/actions/commit_create.ts, src/actions/create_branch.ts, src/actions/submit/push_branch.ts, src/lib/context.ts, src/lib/engine/cache.ts, src/lib/git/commit.ts
=> refactor: thread noVerify to cache instead of context

src/actions/submit/submit_action.ts
=> refactor: minor cleanup

src/actions/create_branch.ts
=> fix: gt bc --restack

src/actions/delete_branch.ts, src/lib/engine/cache.ts
=> fix: restacking for branch delete

src/actions/log.ts, src/actions/show_branch.ts, src/commands/log-commands/default.ts, src/commands/log-commands/short.ts
=> feat: log --reverse

src/actions/log.ts
=> refactor: log.ts to make it easier to move interactive branch selection over

src/lib/engine/parse_branches.ts, src/lib/engine/readBranchesAndMeta.ts, src/lib/utils/splog.ts
=> refactor: move a function and improve logging in prep for persisting cache

src/actions/init.ts, src/commands/dev-commands/meta.ts, src/lib/debug_context.ts, src/lib/engine/cache.ts, src/lib/engine/cache_loader.ts, src/lib/engine/persist_cache.ts, src/lib/engine/readBranchesAndMeta.ts, src/lib/git/get_branch_revision.ts, src/lib/git/get_sha.ts, src/lib/telemetry/profile.ts, test/lib/scenes/trailing_prod_scene.ts
=> feat: first pass at persisting cache

src/commands/autocomplete.ts, src/lib/debug_context.ts, src/lib/engine/metadata_ref.ts, src/lib/engine/readBranchesAndMeta.ts, src/lib/git/sorted_branch_names.ts
=> refactor: rename some things

src/commands/dash-commands/pr.ts
=> feat: dash allows opening prs

src/actions/clean_branches.ts, src/actions/init.ts, test/fast/commands/branch/branch_delete.test.ts, test/fast/commands/repo/init.test.ts, test/fast/commands/repo/sync.test.ts, test/fast/commands/repo/sync_continue.test.ts, test/fast/commands/stacks.test.ts, test/fast/commands/user_config/editor.test.ts, test/fast/commands/user_config/tips.test.ts, test/lib/utils/fake_squash_and_merge.ts
=> chore: fix tests

src/commands/autocomplete.ts
=> feat: add branch track to completion script

package.json, src/commands/autocomplete.ts, yarn.lock
=> feat: add standard yargs completions

src/commands/branch-commands/restack.ts, src/commands/downstack-commands/restack.ts, src/commands/stack-commands/restack.ts, src/commands/upstack-commands/restack.ts
=> feat: add fix and f as aliases for restack

src/actions/edit_branch.ts, src/actions/persist_continuation.ts, src/actions/restack.ts, src/lib/config/continue_config.ts
=> refactor: support persisting branches to sync to continuation

src/lib/runner.ts, test/fast/commands/commit/amend.test.ts, test/fast/commands/commit/amend_continue.test.ts, test/fast/commands/commit/create.test.ts, test/fast/commands/commit/create_continue.test.ts, test/fast/commands/downstack/edit.test.ts, test/fast/commands/downstack/restack.test.ts, test/fast/commands/repo/sync_continue.test.ts, test/fast/commands/stack/restack.test.ts, test/fast/commands/stack/restack_continue.test.ts, test/fast/commands/upstack/onto.test.ts, test/fast/commands/upstack/onto_continue.test.ts, test/fast/commands/upstack/restack.test.ts
=> fix: rebase conflict exit code should be 1

src/lib/engine/cache_loader.ts, src/lib/engine/persist_cache.ts
=> refactor: light cleanup on cache typing

src/actions/sync/clean_branches.ts, src/actions/sync/sync.ts
=> refactor: file was in the wrong folder

src/index.ts
=> fix: add stack trace for uncaught error

src/actions/sync/get_remote_branches.ts
=> fix: bug in dssync + change abort to KilledError

src/actions/sync/get_remote_branches.ts, src/lib/engine/cache.ts, src/lib/git/write_branch.ts
=> fix: dssync should check out the synced branch

src/lib/global_arguments.ts, src/lib/runner.ts
=> fix: improve runner some more

src/lib/debug_context.ts
=> refactor: small simplification of debug_context

src/lib/config/survey_config.ts, src/lib/telemetry/survey/post_survey.ts, src/lib/telemetry/survey/survey.ts
=> fix: remove context dependency for survey bg process

src/lib/telemetry/post_traces.ts
=> fix: remove context dependency for telemetry bg process

src/lib/requests/fetch_pr_info.ts, src/lib/runner.ts
=> fix: weird race bug due to refreshPRInfo needing to load the cache

src/actions/submit/submit_action.ts, src/actions/submit/validate_branches.ts, src/commands/branch-commands/submit.ts, src/commands/upstack-commands/submit.ts, src/lib/engine/cache.ts, src/lib/git/get_sha.ts
=> feat: fail submit if we aren't submitting parent and local parent doesnt match remote

src/lib/engine/cache.ts, src/lib/engine/cache_loader.ts, src/lib/engine/cached_meta.ts
=> refactor: make cached meta readonly

src/actions/submit/prepare_branches.ts
=> fix: small submit_action stuff

src/commands/branch-commands/restack.ts, src/commands/branch-commands/submit.ts, src/commands/downstack-commands/restack.ts, src/commands/upstack-commands/submit.ts
=> feat: i think this looks nicer lol

src/actions/edit_branch.ts
=> fix: limit branch edit to restacked branches to prevent bug

src/lib/engine/parse_branches_and_meta.ts
=> refactor: pull out parentBranchRevision checks into a helper

src/actions/submit/validate_branches.ts, src/index.ts, src/lib/runner.ts, src/lib/telemetry/post_traces.ts, src/lib/telemetry/sigint_handler.ts
=> fix: address nick's comments on runner

src/lib/engine/cache.ts, src/lib/engine/cached_meta.ts, src/lib/engine/parse_branches_and_meta.ts
=> feat: revalidate INVALID_PARENT children when a branch becomes valid

test/fast/commands/branch/track.test.ts, test/fast/commands/upstack/onto.test.ts
=> chore: add test for branch track

src/actions/commit_amend.ts, src/actions/create_branch.ts, src/actions/log.ts, src/actions/submit/submit_action.ts, src/actions/submit/validate_branches.ts, src/actions/sync/sync.ts, src/actions/track_branch.ts, src/lib/engine/cached_meta.ts, src/lib/errors.ts, src/lib/preconditions.ts, src/lib/runner.ts
=> feat: improve error handling + tips

src/lib/engine/cache.ts, src/lib/git/commit_message.ts, src/lib/git/committer_date.ts, src/lib/git/detect_staged_changes.ts, src/lib/git/is_empty_branch.ts, src/lib/git/is_merged.ts, src/lib/git/merge_conflict_help.ts
=> refactor: clean up some options for diff/log

src/lib/engine/cache_loader.ts
=> fix: (maybe) move cache refs

src/actions/create_branch.ts, src/lib/engine/cache.ts, src/lib/git/detect_staged_changes.ts, src/lib/git/diff.ts, src/lib/git/is_empty_branch.ts, src/lib/git/is_merged.ts, src/lib/preconditions.ts
=> fix: bug for really big diffs

.github/workflows/premerge.yml, .gitignore, package.json, yarn.lock
=> test(coveralls): Introduce code coverage

src/actions/submit/submit_action.ts, src/actions/survey.ts, src/background_tasks/fetch_pr_info.ts, src/background_tasks/post_survey.ts, src/background_tasks/upgrade_prompt.ts, src/lib/runner.ts
=> refactor: reorganize files

src/actions/sync_pr_info.ts, src/background_tasks/fetch_pr_info.ts, src/lib/api/pr_info.ts, src/lib/config/pr_info_config.ts, src/lib/context.ts, src/lib/runner.ts
=> fix: pr info doesn't need a context, persists to a temp config file

src/lib/context.ts
=> fix: clear currentBranchOverride

src/commands/dev-commands/cache.ts, src/lib/config/cache_lock_config.ts, src/lib/context.ts, src/lib/engine/cache_lock.ts, src/lib/errors.ts, src/lib/runner.ts, src/lib/telemetry/sigint_handler.ts
=> feat: cache lock to prevent race conditions

.CHANGELOG.md, package.json, src/actions/restack.ts, src/commands/dev-commands/cache.ts, src/index.ts, src/lib/config/cache_lock_config.ts, src/lib/context.ts, src/lib/engine/cache_lock.ts, src/lib/errors.ts, src/lib/runner.ts, src/lib/telemetry/sigint_handler.ts, yarn.lock
=> chore: require node version

.CHANGELOG.md, package.json
=> chore(bump): 0.19.0-alpha.1

.CHANGELOG.md, .github/workflows/premerge.yml, package.json
=> fix: github node version

.github/workflows/pull_request.yml, .github/workflows/push.yml, src/index.ts
=> chore: run CI with multiple node versions

src/actions/edit/edit_downstack.ts, src/actions/edit/stack_edit_file.ts, src/actions/submit/submit_action.ts, src/actions/sync/sync.ts, src/lib/engine/cache.ts
=> refactor: don't include trunk in relativestack

src/actions/commit_amend.ts, src/actions/commit_create.ts, src/actions/create_branch.ts, src/actions/current_branch_onto.ts, src/actions/delete_branch.ts, src/actions/edit/edit_downstack.ts, src/actions/edit/stack_edit_file.ts, src/actions/edit_branch.ts, src/actions/restack.ts, src/actions/submit/submit_action.ts, src/actions/sync/sync.ts, src/commands/branch-commands/restack.ts, src/commands/branch-commands/track.ts, src/commands/downstack-commands/restack.ts, src/commands/stack-commands/restack.ts, src/commands/upstack-commands/restack.ts, src/lib/engine/cache.ts
=> feat: add --parent option to branch track

src/actions/show_branch.ts, src/actions/untrack_branch.ts, src/commands/autocomplete.ts, src/commands/branch-commands/track.ts, src/commands/branch-commands/untrack.ts, src/lib/engine/cache.ts, src/lib/utils/preprocess_command.ts, test/fast/commands/branch/track.test.ts, test/fast/commands/branch/untrack.test.ts
=> feat: gt branch untrack

src/actions/show_branch.ts, src/actions/untrack_branch.ts, src/commands/autocomplete.ts, src/commands/branch-commands/track.ts, src/commands/branch-commands/untrack.ts, src/lib/engine/cache.ts, src/lib/global_arguments.ts, src/lib/utils/preprocess_command.ts, test/fast/commands/branch/track.test.ts, test/fast/commands/branch/untrack.test.ts
=> feat: add descriptions for global args

src/actions/show_branch.ts, src/actions/untrack_branch.ts, src/commands/autocomplete.ts, src/commands/branch-commands/track.ts, src/commands/branch-commands/untrack.ts, src/commands/dash.ts, src/commands/feedback.ts, src/commands/log.ts, src/lib/engine/cache.ts, src/lib/global_arguments.ts, src/lib/utils/preprocess_command.ts, test/fast/commands/branch/track.test.ts, test/fast/commands/branch/untrack.test.ts
=> fix: help for commands with a default

src/actions/create_branch.ts, src/commands/branch-commands/create.ts, test/fast/commands/branch/branch_create.test.ts
=> feat: change --restack to --insert for branch create

src/actions/create_branch.ts, src/commands/branch-commands/create.ts, src/lib/telemetry/tracer.ts, src/lib/utils/exec_sync.ts, test/fast/commands/branch/branch_create.test.ts
=> feat:  more tracer improvments

src/actions/create_branch.ts, src/commands/branch-commands/create.ts, src/lib/telemetry/tracer.ts, src/lib/utils/deprecated_commands.ts, src/lib/utils/exec_sync.ts, src/lib/utils/preprocess_command.ts, src/lib/utils/splog.ts, test/fast/commands/branch/branch_create.test.ts
=> feat: add deprecation warnings

.CHANGELOG.md, src/actions/create_branch.ts, src/commands/branch-commands/create.ts, src/lib/telemetry/tracer.ts, src/lib/utils/deprecated_commands.ts, src/lib/utils/exec_sync.ts, src/lib/utils/preprocess_command.ts, src/lib/utils/splog.ts, test/fast/commands/branch/branch_create.test.ts
=> style: make historical changelog formatting more consistent

.CHANGELOG.md, src/actions/create_branch.ts, src/actions/sync/sync.ts, src/commands/branch-commands/create.ts, src/lib/telemetry/tracer.ts, src/lib/utils/deprecated_commands.ts, src/lib/utils/exec_sync.ts, src/lib/utils/preprocess_command.ts, src/lib/utils/splog.ts, test/fast/commands/branch/branch_create.test.ts
=> feat: add a few hints to sync

.CHANGELOG.md, src/actions/create_branch.ts, src/actions/sync/sync.ts, src/actions/track_branch.ts, src/commands/branch-commands/create.ts, src/commands/branch-commands/track.ts, src/lib/engine/cache.ts, src/lib/telemetry/tracer.ts, src/lib/utils/deprecated_commands.ts, src/lib/utils/exec_sync.ts, src/lib/utils/preprocess_command.ts, src/lib/utils/splog.ts, test/fast/commands/branch/branch_create.test.ts
=> feat: branch track interactive

.CHANGELOG.md, src/actions/checkout_branch.ts, src/actions/create_branch.ts, src/actions/init.ts, src/actions/log.ts, src/actions/sync/sync.ts, src/actions/track_branch.ts, src/commands/branch-commands/checkout.ts, src/commands/branch-commands/create.ts, src/commands/branch-commands/track.ts, src/commands/upstack-commands/onto.ts, src/lib/engine/cache.ts, src/lib/telemetry/tracer.ts, src/lib/utils/deprecated_commands.ts, src/lib/utils/exec_sync.ts, src/lib/utils/preprocess_command.ts, src/lib/utils/splog.ts, test/fast/commands/branch/branch_create.test.ts
=> feat: bco and uso interactive to use autocomplete

src/actions/init.ts, src/actions/track_branch.ts, src/lib/engine/cache.ts, test/lib/scenes/trailing_prod_scene.ts
=> feat: add onboarding flow to repo init

src/lib/runner.ts, src/lib/telemetry/sigint_handler.ts
=> fix: telemetry wasn't working for alpha

src/actions/init.ts, src/actions/log.ts
would pull this out into a common helper but i'm too happy — need to go through refactor all the prompts into the IO lib before we move to GUI anyway so whatever for now
=> feat: allow mid-word autocompletion for branch selection

src/actions/log.ts, src/background_tasks/post_survey.ts, src/background_tasks/upgrade_prompt.ts, src/commands/auth.ts, src/commands/demo.ts, src/commands/dev-commands/cache.ts, src/commands/log-commands/default.ts, src/commands/log-commands/short.ts, src/commands/repo-commands/repo_init.ts, src/commands/user-commands/branch_date.ts, src/commands/user-commands/branch_prefix.ts, src/commands/user-commands/branch_replacement.ts, src/commands/user-commands/editor.ts, src/commands/user-commands/tips.ts, src/lib/config/compose_config.ts, src/lib/context.ts, src/lib/runner.ts, src/lib/telemetry/sigint_handler.ts, src/lib/utils/branch_name.ts, test/lib/scenes/abstract_scene.ts
=> feat: log --stack

src/actions/log.ts, src/commands/log-commands/default.ts, src/commands/log-commands/short.ts
=> feat: log --steps

src/actions/edit_branch.ts, src/actions/log.ts, src/actions/print_conflict_status.ts, src/actions/restack.ts, src/commands/log-commands/default.ts, src/commands/log-commands/short.ts, src/lib/errors.ts, src/lib/git/merge_conflict_help.ts, src/lib/runner.ts
=> feat: add log --steps 3 to rebase conflict

src/actions/delete_branch.ts, src/actions/print_conflict_status.ts, src/index.ts
=> fix: should use chalk.redBright instead of red everywhere

.CHANGELOG.md, package.json
=> chore(bump): 0.19.0-alpha.2

.CHANGELOG.md, package.json, src/actions/show_branch.ts
=> feat: this ones for you nick

.CHANGELOG.md, package.json, src/actions/show_branch.ts, src/actions/submit/prepare_branches.ts, src/actions/submit/validate_branches.ts
=> perf: speed up submit

src/lib/engine/metadata_ref.ts, src/lib/utils/git_repo.ts, test/fast/commands/repo/sync.test.ts, test/lib/scenes/trailing_prod_scene.ts
trying to decrease surface area of the execSync command string, ripe place for bugs
=> fix: simplify unnecessary git -C

src/lib/engine/metadata_ref.ts, src/lib/runner.ts, src/lib/telemetry/tracer.ts, src/lib/utils/git_repo.ts, test/fast/commands/repo/sync.test.ts, test/lib/scenes/trailing_prod_scene.ts
This one is parity with 0.18.7 - we need to throw the error into the span for it to show up in DD traces
=> fix: tracing didn't include error

src/lib/engine/cache.ts, src/lib/engine/cache_loader.ts, src/lib/engine/parse_branches_and_meta.ts
=> style: options/var names for cache loading

package.json, yarn.lock
=> chore: bump retype

src/actions/create_branch.ts
=> feat: improve hint slightly

src/actions/create_branch.ts, src/actions/log.ts
=> fix: formatting for log --stack

src/actions/create_branch.ts, src/actions/log.ts, src/commands/branch-commands/restack.ts, src/commands/downstack-commands/restack.ts, src/lib/pre-yargs/deprecated_commands.ts
=> feat: add deprecation warning for fix/f

src/actions/create_branch.ts, src/actions/log.ts, src/actions/submit/prepare_branches.ts, src/actions/submit/submit_action.ts, src/actions/submit/validate_branches.ts, src/actions/sync/sync.ts, src/commands/branch-commands/restack.ts, src/commands/downstack-commands/restack.ts, src/lib/pre-yargs/deprecated_commands.ts, src/lib/utils/splog.ts
=> feat: add emojis to repo sync

src/actions/submit/prepare_branches.ts
=> feat: submit branchname formatting

src/actions/submit/validate_branches.ts, src/lib/runner.ts
=> fix: unhandled promise

.github/workflows/push.yml
=> ci: fix node version

src/lib/utils/escape_for_shell.ts
=> fix: node v14 support

src/index.ts
=> fix: node warnings on v18 once and for all (hopefully)

.husky/commit-msg, .husky/pre-commit, package.json, yarn.lock
=> fix: remove precommit hooks to unblock brew

.CHANGELOG.md, package.json
=> chore(bump): 0.19.1

src/actions/sync/get.ts, src/lib/engine/cache.ts, src/lib/git/fetch_branch.ts
=> fix: ds get typo

src/actions/submit/submit_action.ts, src/actions/sync/get.ts, src/lib/engine/cache.ts, src/lib/git/fetch_branch.ts
=> feat: switch out submit push emoji

src/actions/edit_branch.ts, src/actions/persist_continuation.ts, src/actions/restack.ts, src/actions/submit/submit_action.ts, src/actions/sync/get.ts, src/lib/config/continue_config.ts, src/lib/engine/cache.ts, src/lib/git/fetch_branch.ts, src/lib/git/rebase.ts
=> fix: persist rebasedBranchBase in continuation config

src/actions/continue.ts, src/actions/restack.ts, src/actions/sync/get.ts, src/commands/continue.ts, src/lib/engine/cache.ts, src/lib/git/rebase.ts
=> feat: support rebase on get

src/actions/continue.ts, src/actions/edit_branch.ts, src/actions/persist_continuation.ts, src/actions/restack.ts, src/actions/submit/submit_action.ts, src/actions/submit/validate_branches.ts, src/actions/sync/get.ts, src/commands/continue.ts, src/lib/config/continue_config.ts, src/lib/engine/cache.ts, src/lib/git/fetch_branch.ts, src/lib/git/rebase.ts
=> fix: submit abort on empty branch bug

.CHANGELOG.md, package.json, src/actions/continue.ts, src/actions/edit_branch.ts, src/actions/persist_continuation.ts, src/actions/restack.ts, src/actions/submit/submit_action.ts, src/actions/submit/validate_branches.ts, src/actions/sync/get.ts, src/commands/continue.ts, src/lib/config/continue_config.ts, src/lib/engine/cache.ts, src/lib/git/fetch_branch.ts, src/lib/git/rebase.ts
=> chore(bump): 0.19.2

src/commands/completion.ts
=> fix: visibility on help string for gt completion

src/actions/log.ts, src/actions/log_short_classic.ts
**Context:**
After user reports that the new `gt ls` appears confusing, figured out a way to improve the display to address them.
Implement the new view.
**Test Plan:**
=> feat: update log short to discussed design

src/actions/sync/get.ts
I'm going to actually start filling in PR descriptions, seems like a good habit. 
**Context:**
A user reported that running `downstack get` failed with a confusing error.  It turned out that the `getParentPrecondition` was failing because we had an incorrect implicit assumption that if the branch we `get` exists locally, it is tracked.
This change removes that assumption, allowing untracked branches to be overwritten by `get`, and adds slightly different copy for when Graphite sees a branch that is untracked vs. has a different parent locally.  Pulled out a little helper function to keep the logic to overwrite/abort the same.
**Test Plan:**
I plan on adding cohesive testing for `ds get` upstack
=> fix: issue with get for untracked branches

src/background_tasks/post_traces.ts
=> fix: typo from literally a year ago

src/actions/show_branch.ts
=> feat: show commit of master in branch info

src/actions/show_branch.ts
=> feat: show commit of master in log

src/actions/init.ts, src/actions/show_branch.ts, src/commands/repo-commands/repo_init.ts, src/commands/user-commands/restack_date.ts, src/lib/config/user_config.ts, src/lib/context.ts, src/lib/engine/cache.ts, src/lib/git/rebase.ts, src/lib/runner.ts
=> feat: add user config option to pass --committer-date-is-author-date to git rebase

src/actions/branch_traversal.ts
=> feat: add autocomplete for branch up disambiguation

src/lib/pre-yargs/preprocess_command.ts
=> feat: allow gt dpr for dash pr

src/lib/engine/cache_loader.ts, src/lib/engine/parse_branches_and_meta.ts
=> feat: invalidate cache on upgrade

src/lib/config/cache_persistence_config.ts, src/lib/engine/cached_meta.ts, src/lib/engine/metadata_ref.ts
=> refactor: actually validate meta with retype

src/actions/rename_branch.ts, src/commands/branch-commands/rename.ts
**Context:**
[Linear ticket](https://linear.app/screenplay/issue/GT-4891/gt-branch-rename-interactive-mode)
note: still need to add unit tests
**Test Plan:**
```
╰─❯ yarn cli branch rename --force                                     
Enter new name for branch
)} ▸ jgb-4891:
✔ Branch Name … jgb-4891-2
Successfully renamed jgb-4891 to jgb-4891-2
```
=> feat: interactive mode for gt branch rename

.CHANGELOG.md, package.json
=> chore(bump): 0.19.4

.github/PULL_REQUEST_TEMPLATE.md
=> chore: PR template formatting

src/actions/init.ts, src/actions/track_branch.ts
=> fix: prompts cancel behavior

src/actions/init.ts, src/actions/track_branch.ts, src/lib/pre-yargs/preprocess_command.ts
=> fix: running gt with no args

src/actions/fold_branch.ts, src/commands/branch-commands/fold.ts, src/lib/engine/cache.ts, test/fast/commands/branch/branch_fold.test.ts
**Context:**
Add a new command to fold one branch into another
implement new command and add tests
**Test Plan:**
added tests + manual testing
=> feat: gt branch fold

src/actions/fold_branch.ts, src/actions/squash.ts, src/actions/submit/prepare_branches.ts, src/commands/branch-commands/fold.ts, src/commands/branch-commands/squash.ts, src/lib/engine/cache.ts, src/lib/git/commit_range.ts, src/lib/git/reset_branch.ts, src/lib/pre-yargs/preprocess_command.ts, test/fast/commands/branch/branch_fold.test.ts, test/fast/commands/branch/branch_squash.test.ts
=> feat: branch squash

src/actions/fold_branch.ts, src/actions/squash.ts, src/actions/submit/prepare_branches.ts, src/actions/track_branch.ts, src/commands/branch-commands/fold.ts, src/commands/branch-commands/squash.ts, src/commands/downstack-commands/track.ts, src/lib/engine/cache.ts, src/lib/git/commit_range.ts, src/lib/git/reset_branch.ts, src/lib/pre-yargs/preprocess_command.ts, test/fast/commands/branch/branch_fold.test.ts, test/fast/commands/branch/branch_squash.test.ts, test/fast/commands/downstack/track.test.ts
=> feat: downstack track

.CHANGELOG.md, package.json, src/actions/fold_branch.ts, src/actions/squash.ts, src/actions/submit/prepare_branches.ts, src/actions/track_branch.ts, src/commands/branch-commands/fold.ts, src/commands/branch-commands/squash.ts, src/commands/downstack-commands/track.ts, src/lib/engine/cache.ts, src/lib/git/commit_range.ts, src/lib/git/reset_branch.ts, src/lib/pre-yargs/preprocess_command.ts, test/fast/commands/branch/branch_fold.test.ts, test/fast/commands/branch/branch_squash.test.ts, test/fast/commands/downstack/track.test.ts
=> chore(bump): v0.19.5

src/actions/rename_branch.ts, src/commands/downstack-commands/test.ts, src/commands/downstack-commands/track.ts, src/lib/engine/cache.ts, src/lib/pre-yargs/preprocess_command.ts, test/fast/commands/branch/branch_rename.test.ts
=> fix: aliases

src/actions/log.ts, src/actions/print_conflict_status.ts, src/lib/context.ts, src/lib/spiffy/continuation_spf.ts, test/fast/commands/commit/amend_continue.test.ts, test/fast/commands/commit/create_continue.test.ts
=> fix: continue state management

src/actions/create_branch.ts, src/actions/show_branch.ts, src/actions/track_branch.ts, src/lib/git/commit.ts, test/fast/actions/submit_action.test.ts
=> feat: no longer create empty commit on bc with no changes

src/actions/create_branch.ts, src/actions/show_branch.ts, src/actions/track_branch.ts, src/lib/git/commit.ts, src/lib/git/write_branch.ts, test/fast/actions/submit_action.test.ts
=> fix: quiet forceCreate

src/actions/branch_traversal.ts, src/actions/create_branch.ts, src/actions/init.ts, src/actions/log.ts, src/actions/show_branch.ts, src/actions/submit/validate_branches.ts, src/actions/track_branch.ts, src/lib/git/commit.ts, src/lib/git/write_branch.ts, src/lib/utils/prompts_helpers.ts, test/fast/actions/submit_action.test.ts
=> feat: add note about submitting a branch that is not restacked on trunk

src/actions/branch_traversal.ts, src/actions/create_branch.ts, src/actions/init.ts, src/actions/log.ts, src/actions/show_branch.ts, src/actions/submit/prepare_branches.ts, src/actions/submit/validate_branches.ts, src/actions/track_branch.ts, src/lib/git/commit.ts, src/lib/git/write_branch.ts, src/lib/utils/prompts_helpers.ts, test/fast/actions/submit_action.test.ts
=> fix: submit --no-edit printout

src/actions/branch_traversal.ts, src/actions/create_branch.ts, src/actions/init.ts, src/actions/log.ts, src/actions/show_branch.ts, src/actions/submit/prepare_branches.ts, src/actions/submit/validate_branches.ts, src/actions/track_branch.ts, src/commands/branch-commands/submit.ts, src/commands/downstack-commands/submit.ts, src/commands/shared-commands/submit.ts, src/commands/stack-commands/submit.ts, src/commands/upstack-commands/submit.ts, src/lib/git/commit.ts, src/lib/git/write_branch.ts, src/lib/utils/prompts_helpers.ts, test/fast/actions/submit_action.test.ts
=> feat: add -n for submit --no-edit

package.json, scripts/node_version.js, src/index.ts
=> fix: error message on node <14

package.json
=> fix(package_json): update the main path

src/index.ts
=> feat: link to docs in man page

src/lib/engine/cache.ts, src/lib/git/commit_range.ts
=> fix: log on init commit

src/lib/engine/cache.ts, src/lib/engine/parse_branches_and_meta.ts
=> feat: cycle detection for metacache

src/commands/downstack-commands/track.ts, src/lib/engine/cache.ts, src/lib/engine/parse_branches_and_meta.ts, test/fast/commands/downstack/restack.test.ts, test/fast/commands/downstack/track.test.ts
=> feat: ds track takes branch name

src/actions/continue.ts, src/actions/sync/get.ts, src/commands/downstack-commands/get.ts, src/commands/shared-commands/submit.ts
=> feat: downstack get --force

package.json, src/commands/feedback-commands/default.ts, yarn.lock
=> feat: send up auth on feedback

src/actions/submit/pr_body.ts
=> fix: filetype for PR body

src/lib/engine/cache_loader.ts
=> perf: use native hashing instead of calling git

src/actions/test.ts
=> fix: test commands

src/actions/test.ts, src/commands/branch-commands/checkout.ts, src/commands/branch-commands/create.ts, src/commands/branch-commands/delete.ts, src/commands/branch-commands/rename.ts, src/commands/branch-commands/track.ts, src/commands/branch-commands/untrack.ts, src/commands/dash-commands/pr.ts, src/commands/dev-commands/meta.ts, src/commands/downstack-commands/get.ts, src/commands/downstack-commands/test.ts, src/commands/downstack-commands/track.ts, src/commands/feedback-commands/default.ts, src/commands/stack-commands/test.ts, src/commands/upstack-commands/onto.ts, src/commands/upstack-commands/test.ts
=> fix: hide positional arguments from help

src/actions/init.ts, src/actions/test.ts, src/commands/branch-commands/checkout.ts, src/commands/branch-commands/create.ts, src/commands/branch-commands/delete.ts, src/commands/branch-commands/rename.ts, src/commands/branch-commands/track.ts, src/commands/branch-commands/untrack.ts, src/commands/dash-commands/pr.ts, src/commands/dev-commands/meta.ts, src/commands/downstack-commands/get.ts, src/commands/downstack-commands/test.ts, src/commands/downstack-commands/track.ts, src/commands/feedback-commands/default.ts, src/commands/stack-commands/test.ts, src/commands/upstack-commands/onto.ts, src/commands/upstack-commands/test.ts
=> feat: update repo init copy

src/actions/submit/prepare_branches.ts, src/actions/submit/submit_action.ts
=> fix: submit --no-edit and --no-interactive

src/actions/submit/prepare_branches.ts, src/actions/submit/submit_action.ts, src/actions/submit/submit_prs.ts
=> refactor: clean up submit code

src/actions/submit/submit_prs.ts
=> fix: better error message on GH submit error

src/lib/engine/metadata_ref.ts, src/lib/git/rebase.ts, src/lib/git/switch_branch.ts, test/lib/utils/fake_squash_and_merge.ts
=> fix: remove all stdio ignores

src/lib/engine/metadata_ref.ts, src/lib/git/delete_branch.ts, src/lib/git/fetch_branch.ts, src/lib/git/pull_branch.ts, src/lib/git/rebase.ts, src/lib/git/switch_branch.ts, src/lib/git/write_branch.ts, test/lib/utils/fake_squash_and_merge.ts
=> fix: replace quiet with pipe for tracing

src/lib/git/rebase.ts
these should have been 'ignore' instead of 'throw'
=> fix: rebase bug due to not catching error

src/actions/split.ts, src/lib/engine/cache.ts, src/lib/git/branch_ops.ts, src/lib/git/reset_branch.ts
=> feat: start split

src/lib/git/branch_ops.ts, src/lib/git/commit.ts, src/lib/git/commit_range.ts, src/lib/git/diff.ts, test/actions/submit_action.test.ts
=> feat: add options to commit for split

src/lib/git/branch_ops.ts, src/lib/git/commit.ts, src/lib/git/commit_range.ts, src/lib/git/diff.ts, test/actions/submit_action.test.ts
=> feat: add force option to switch

src/actions/split.ts, src/lib/engine/cache.ts, src/lib/git/branch_ops.ts, src/lib/git/commit.ts, src/lib/git/commit_range.ts, src/lib/git/diff.ts, test/actions/submit_action.test.ts
=> feat: split

src/actions/split.ts, src/commands/branch-commands/split.ts
[split style.mov](https://graphite-user-uploaded-assets.s3.amazonaws.com/t6FDnC5t98Dwamvf2BHI/c4ebb413-94ca-4a74-801c-c9a41faa4bb9/split%20style.mov)
=> feat: split style selection

src/actions/commit_amend.ts, src/actions/commit_create.ts, src/actions/create_branch.ts, src/actions/split.ts, src/commands/branch-commands/create.ts, src/commands/branch-commands/split.ts, src/commands/commit-commands/amend.ts, src/commands/commit-commands/create.ts, src/lib/engine/cache.ts, src/lib/git/branch_ops.ts, src/lib/git/commit.ts, src/lib/git/commit_range.ts, src/lib/git/diff.ts, test/actions/submit_action.test.ts
for `branch create`, `commit create`, `commit amend` — might as well throw this in while i'm here.  still need to add autostashing for this to be useful midstack, but handy at the tip i imagine
=> feat: add --patch flag

src/actions/split.ts
the helper used to do name + commit creation, now it just does naming so that it can be used by `split -c`
=> refactor: pull out branch name prompt so it can be used in both versions of split

src/actions/split.ts, src/lib/engine/cache.ts
address some of gregs downstack comments
=> style: clarify some split naming

src/actions/split.ts, src/lib/engine/cache.ts
will add commit history to naming part upstack
[Screen Recording 2022-07-17 at 22.33.32.mov](https://graphite-user-uploaded-assets.s3.amazonaws.com/t6FDnC5t98Dwamvf2BHI/2d98e5c3-f4f2-4aac-a938-35d1af2e5556/Screen%20Recording%202022-07-17%20at%2022.33.32.mov)
=> feat: split by commit

src/actions/commit_amend.ts, src/actions/commit_create.ts, src/actions/create_branch.ts, src/actions/log.ts, src/actions/split.ts, src/commands/branch-commands/create.ts, src/commands/branch-commands/split.ts, src/commands/commit-commands/amend.ts, src/commands/commit-commands/create.ts, src/lib/colors.ts, src/lib/engine/cache.ts, src/lib/git/branch_ops.ts, src/lib/git/commit.ts, src/lib/git/commit_range.ts, src/lib/git/diff.ts, test/actions/submit_action.test.ts
this is important for hunk split — if branch's file contents have not changed but commit hash has we should definitely update the PR
=> fix: detectUnsubmittedChanges should check revision not diff

src/actions/commit_amend.ts, src/actions/commit_create.ts, src/actions/create_branch.ts, src/actions/log.ts, src/actions/split.ts, src/commands/branch-commands/create.ts, src/commands/branch-commands/split.ts, src/commands/commit-commands/amend.ts, src/commands/commit-commands/create.ts, src/lib/colors.ts, src/lib/engine/cache.ts, src/lib/git/branch_ops.ts, src/lib/git/commit.ts, src/lib/git/commit_range.ts, src/lib/git/diff.ts, src/lib/utils/exec_sync.ts, test/actions/submit_action.test.ts
=> refactor: remove now unused printstdout option on exec sync

src/actions/commit_amend.ts, src/actions/commit_create.ts, src/actions/create_branch.ts, src/actions/log.ts, src/actions/split.ts, src/commands/branch-commands/create.ts, src/commands/branch-commands/split.ts, src/commands/commit-commands/amend.ts, src/commands/commit-commands/create.ts, src/lib/colors.ts, src/lib/engine/cache.ts, src/lib/git/branch_ops.ts, src/lib/git/commit.ts, src/lib/git/commit_range.ts, src/lib/git/diff.ts, src/lib/preconditions.ts, src/lib/utils/exec_sync.ts, test/actions/submit_action.test.ts
Easy one, consistency with the rest of the codebase
=> style: exports to single line

src/actions/checkout_branch.ts, src/actions/init.ts, src/actions/log.ts, src/commands/branch-commands/checkout.ts
the first of better support for working with untracked branches
=> feat: show untracked branches in interactive checkout

src/actions/split.ts
this addresses a lot of gregs comments earlier in the stack (not the ones for cache.ts) and makes the rest of the code more readable
=> refactor: clean up split.ts

src/actions/split.ts
=> feat: show commits for split branch naming

src/actions/log.ts, src/commands/log-commands/default.ts, src/commands/log-commands/short.ts
=> feat: untracked branches in log and log short

src/actions/log.ts, src/actions/submit/pr_body.ts, src/commands/log-commands/default.ts, src/commands/log-commands/short.ts, src/commands/user-commands/submit_body.ts, src/lib/spiffy/user_config_spf.ts, test/actions/submit_action.test.ts, test/lib/scenes/abstract_scene.ts
=> feat: allow toggling of commit messages in pr body

src/actions/branch_traversal.ts, src/actions/checkout_branch.ts, src/actions/log.ts, src/actions/submit/pr_body.ts, src/actions/submit/validate_branches.ts, src/commands/log-commands/default.ts, src/commands/log-commands/short.ts, src/commands/user-commands/submit_body.ts, src/lib/spiffy/user_config_spf.ts, test/actions/submit_action.test.ts, test/lib/scenes/abstract_scene.ts
=> feat: info on checkout

.eslintrc, src/actions/branch_traversal.ts, src/actions/checkout_branch.ts, src/actions/log.ts, src/actions/submit/pr_body.ts, src/actions/submit/validate_branches.ts, src/commands/log-commands/default.ts, src/commands/log-commands/short.ts, src/commands/user-commands/submit_body.ts, src/index.ts, src/lib/pre-yargs/passthrough.ts, src/lib/spiffy/user_config_spf.ts, src/lib/utils/splog.ts, test/actions/submit_action.test.ts, test/lib/scenes/abstract_scene.ts
=> chore: no-console

.eslintrc, src/actions/branch_traversal.ts, src/actions/checkout_branch.ts, src/actions/log.ts, src/actions/submit/pr_body.ts, src/actions/submit/validate_branches.ts, src/commands/log-commands/default.ts, src/commands/log-commands/short.ts, src/commands/user-commands/submit_body.ts, src/index.ts, src/lib/git/push_branch.ts, src/lib/pre-yargs/passthrough.ts, src/lib/spiffy/user_config_spf.ts, src/lib/utils/splog.ts, test/actions/submit_action.test.ts, test/lib/scenes/abstract_scene.ts
=> fix: remove stderr redirect from push

.eslintrc, src/actions/branch_traversal.ts, src/actions/checkout_branch.ts, src/actions/log.ts, src/actions/submit/pr_body.ts, src/actions/submit/validate_branches.ts, src/commands/log-commands/default.ts, src/commands/log-commands/short.ts, src/commands/user-commands/submit_body.ts, src/index.ts, src/lib/git/push_branch.ts, src/lib/pre-yargs/passthrough.ts, src/lib/spiffy/user_config_spf.ts, src/lib/utils/splog.ts, test/actions/submit_action.test.ts, test/lib/scenes/abstract_scene.ts
=> fix: log short --stack

.eslintrc, src/actions/branch_traversal.ts, src/actions/checkout_branch.ts, src/actions/log.ts, src/actions/submit/pr_body.ts, src/actions/submit/prepare_branches.ts, src/actions/submit/submit_action.ts, src/actions/submit/validate_branches.ts, src/commands/branch-commands/submit.ts, src/commands/downstack-commands/submit.ts, src/commands/log-commands/default.ts, src/commands/log-commands/short.ts, src/commands/shared-commands/submit.ts, src/commands/stack-commands/submit.ts, src/commands/upstack-commands/submit.ts, src/commands/user-commands/submit_body.ts, src/index.ts, src/lib/git/push_branch.ts, src/lib/pre-yargs/passthrough.ts, src/lib/spiffy/user_config_spf.ts, src/lib/utils/splog.ts, test/actions/submit_action.test.ts, test/lib/scenes/abstract_scene.ts
similar to `--confirm` but on a per-branch basis.
[submit select.mov](https://graphite-user-uploaded-assets.s3.amazonaws.com/t6FDnC5t98Dwamvf2BHI/5a954fe2-a1b3-4380-8a0a-28a29a6028d2/submit%20select.mov)
=> feat: add --select for submit

.gitignore, package.json, yarn.lock
the mac version seems to work, need to add an abstraction to run it instead of the node version in our tests though, will do upstack!
=> chore: add pkg

src/actions/submit/submit_prs.ts
=> fix: error parsing bug

src/actions/show_branch.ts, src/actions/submit/submit_prs.ts, src/commands/branch-commands/info.ts, src/lib/git/diff.ts
=> feat: add --diff to branch info

src/actions/init.ts, src/actions/show_branch.ts, src/actions/split.ts, src/actions/submit/submit_prs.ts, src/commands/branch-commands/info.ts, src/lib/git/diff.ts
=> fix: address demo comments on split

src/actions/init.ts, src/actions/log.ts, src/actions/show_branch.ts, src/actions/split.ts, src/actions/submit/submit_prs.ts, src/commands/branch-commands/info.ts, src/lib/git/diff.ts, src/lib/utils/prompts_helpers.ts
=> feat: clear prompt line on bco and uso

src/actions/checkout_branch.ts
=> fix: checkout copy for trunk

src/lib/git/push_branch.ts
=> feat: set upstream on push

.CHANGELOG.md, .github/CODEOWNERS, package.json, src/background_tasks/post_traces.ts, src/background_tasks/upgrade_prompt.ts, src/lib/utils/git_repo.ts, src/lib/utils/spawn.ts
=> chore(bump): 0.20.0

.CHANGELOG.md, package.json, src/background_tasks/post_traces.ts
=> chore(bump): v0.20.3

src/actions/submit/submit_prs.ts, src/actions/sync/get.ts, src/actions/sync/sync.ts, src/lib/errors.ts
=> refactor: remove unnecessary exception wrap

src/actions/submit/submit_prs.ts, src/actions/sync/get.ts, src/actions/sync/sync.ts, src/actions/test.ts, src/lib/errors.ts
=> feat: make stack test cooler

src/actions/log.ts
=> fix: -u option for gt bco

src/actions/log.ts, src/actions/print_conflict_status.ts, src/lib/context.ts, src/lib/engine/cache_loader.ts, src/lib/engine/parse_branches_and_meta.ts, src/lib/git/merge_conflict_help.ts, test/commands/stack/restack_continue.test.ts
=> fix: rebase --abort current branch cache inconsistency

.CHANGELOG.md, package.json, src/actions/log.ts, src/actions/print_conflict_status.ts, src/commands/changelog.ts, src/commands/dash-commands/default.ts, src/commands/docs.ts, src/lib/context.ts, src/lib/engine/cache_loader.ts, src/lib/engine/parse_branches_and_meta.ts, src/lib/git/merge_conflict_help.ts, test/commands/stack/restack_continue.test.ts
=> chore(bump): v0.20.4

.eslintrc, .vscode/settings.json, package.json, yarn.lock
=> chore: eslint-prettier for cli

src/actions/edit/edit_downstack.ts, src/actions/submit/pr_body.ts, src/commands/dev-commands/meta.ts, src/lib/spiffy/user_config_spf.ts
=> fix: editor with spaces in it

package.json, src/commands/changelog.ts
=> fix: changelog

.CHANGELOG.md, package.json
=> chore(bump): 0.20.5

src/actions/split.ts
this makes track the command to start using graphite with big branches
=> feat: track before split

src/lib/git/rebase.ts
=> fix: branch edit

src/actions/submit/pr_body.ts, src/lib/git/rebase.ts, test/actions/submit_action.test.ts
=> feat: require confirmation before using aborted submit body

.CHANGELOG.md, package.json
=> chore(bump): 0.20.6

src/actions/submit/prepare_branches.ts
=> fix: --no-edit shouldn't automatically make new prs draft

src/actions/log.ts
=> refactor: logAction to be more amenable to a pager

src/actions/log.ts, src/lib/context.ts, src/lib/git/git_editor.ts, src/lib/spiffy/user_config_spf.ts, src/lib/utils/splog.ts
=> feat: add pager for log

src/actions/log.ts, src/commands/changelog.ts, src/lib/context.ts, src/lib/git/git_editor.ts, src/lib/spiffy/user_config_spf.ts, src/lib/utils/splog.ts
=> feat: add pager for changelog

src/actions/submit/pr_body.ts
Because the filename is constant, not creating a new directory each time meant we would fail if someone quit the submit process in the middle of writing their description but then still saved the file.
To fix we create a new dir every time.
Also put cleanup in a finally — that's just good practice.
=> fix: lingering pr body edit file

package.json
=> chore: add repo to package

src/actions/show_branch.ts, src/lib/git/diff.ts, src/lib/git/show_commits.ts
=> feat: add pager for branch info

src/actions/show_branch.ts, src/commands/user-commands/editor.ts, src/commands/user-commands/pager.ts, src/lib/git/diff.ts, src/lib/git/show_commits.ts, src/lib/spiffy/user_config_spf.ts, test/commands/user_config/editor.test.ts, test/commands/user_config/pager.test.ts
=> feat: allow pager configuration

src/actions/show_branch.ts, src/commands/branch-commands/info.ts, src/commands/user-commands/editor.ts, src/commands/user-commands/pager.ts, src/lib/git/diff.ts, src/lib/git/show_commits.ts, src/lib/spiffy/user_config_spf.ts, test/commands/user_config/editor.test.ts, test/commands/user_config/pager.test.ts
=> refactor: rename fn

src/actions/show_branch.ts, src/commands/branch-commands/info.ts, src/commands/user-commands/editor.ts, src/commands/user-commands/pager.ts, src/lib/git/diff.ts, src/lib/git/show_commits.ts, src/lib/spiffy/user_config_spf.ts, test/commands/user_config/editor.test.ts, test/commands/user_config/pager.test.ts
=> fix: color for gt bi -p

src/actions/show_branch.ts, src/commands/branch-commands/info.ts, src/commands/user-commands/editor.ts, src/commands/user-commands/pager.ts, src/lib/git/diff.ts, src/lib/git/show_commits.ts, src/lib/spiffy/user_config_spf.ts, src/lib/utils/run_command.ts, test/commands/user_config/editor.test.ts, test/commands/user_config/pager.test.ts
=> fix: increase buffer size for spawn

src/actions/show_branch.ts, src/commands/branch-commands/info.ts, src/commands/user-commands/editor.ts, src/commands/user-commands/pager.ts, src/lib/git/diff.ts, src/lib/git/show_commits.ts, src/lib/spiffy/user_config_spf.ts, src/lib/utils/run_command.ts, test/commands/user_config/editor.test.ts, test/commands/user_config/pager.test.ts
=> fix: unsubmittedChanges diff command

src/actions/create_branch.ts, src/lib/engine/cache.ts, src/lib/git/commit.ts, src/lib/utils/run_command.ts
=> refactor: kill rollbackonerror for commit

src/commands/demo.ts
=> refactor: remove runCommand dependency in gt demo

src/lib/utils/git_repo.ts
=> refactor: remove runCommand dependency in git_repo

test/actions/remote_actions.test.ts, test/commands/branch/branch_create.test.ts
=> refactor: remove dependcy on git client internals from tests

apps/cli/.CHANGELOG.md, apps/cli/package.json
**Context:**
Releasing version `0.20.19`.
Version bump and changelog update.
**Test Plan:**
n/a
=> chore(bump): 0.20.19

apps/gti-client/README.md, apps/gti-client/src/DownloadCommitsMenu.scss, apps/gti-client/src/DownloadCommitsMenu.tsx, apps/gti-client/src/DropdownFields.tsx, apps/gti-client/src/PullButton.tsx, apps/gti-client/src/TopBar.tsx, apps/gti-client/src/operations/DownstackGetOperation.ts, apps/gti-server/README.md, apps/vscode/CONTRIBUTING.md, libs/gti-shared/README.md, libs/gti-shared/src/analytics/eventNames.ts
=> feat: downstack get

apps/gti-client/src/config_observable.ts, apps/gti-client/src/gettingStarted/GettingStartedModal.tsx
=> fix: nux show

apps/gti-client/src/operations/PrSubmitOperation.ts
=> fix: branch submit

apps/gti-client/src/operations/AmendOperation.ts
don't wipe out the commit message when we amend with no message provided
**Context:**
**Test Plan:**
=> fix: amend --no-edit

apps/gti-client/src/operations/CommitOperation.ts
=> fix: don't put whole description into branch name

apps/gti-client/src/operations/AmendOperation.ts
=> fix: prevent interactive commit create

apps/cli/package.json, yarn.lock
=> chore: bump gti-cli-routes version number

apps/cli/src/actions/submit/submit_action.ts, apps/cli/src/actions/submit/submit_prs.ts, apps/cli/src/commands/branch-commands/submit.ts, apps/cli/src/commands/downstack-commands/submit.ts, apps/cli/src/commands/shared-commands/submit.ts, apps/cli/src/commands/stack-commands/submit.ts, apps/cli/src/commands/upstack-commands/submit.ts
**Context:**
Merge when ready from the CLI.
Add --merge-when-ready and -m as cli flags for submit endpoints, and trigger merge-when-ready when these flags are used.
**Test Plan:**
=> feat: pass merge when ready command line flag to the server

apps/gti-client/src/UncommittedChanges.tsx
=> fix: uncommitted changes behavior and copy

apps/cli/src/actions/branch_traversal.ts, apps/cli/src/actions/init.ts, apps/cli/src/actions/log.ts, apps/cli/src/actions/rename_branch.ts, apps/cli/src/actions/split.ts, apps/cli/src/actions/submit/pr_body.ts, apps/cli/src/actions/submit/pr_draft.ts, apps/cli/src/actions/submit/pr_title.ts, apps/cli/src/actions/submit/prepare_branches.ts, apps/cli/src/actions/submit/reviewers.ts, apps/cli/src/actions/submit/submit_action.ts, apps/cli/src/actions/submit/validate_branches.ts, apps/cli/src/actions/survey.ts, apps/cli/src/actions/sync/clean_branches.ts, apps/cli/src/actions/sync/get.ts, apps/cli/src/actions/sync/sync.ts, apps/cli/src/actions/track_branch.ts, apps/cli/src/actions/untrack_branch.ts, apps/cli/src/lib/context.ts, apps/cli/src/lib/errors.ts, apps/cli/src/lib/utils/pr_templates.ts, apps/cli/src/lib/utils/prompts_helpers.ts, apps/cli/test/actions/submit/prepare_branches.test.ts, apps/cli/test/actions/submit/reviewers.test.ts, apps/cli/test/lib/scenes/abstract_scene.ts
=> feat: safeguard against prompts from gti

apps/gti-client/src/Commit.tsx
=> fix: only show needs update if not closed (and branch was deleted).
