src/commands/diff/index.ts, src/commands/fix/index.ts, src/commands/next-or-prev/index.ts, src/commands/print-stacks/index.ts, src/commands/restack/index.ts, src/commands/submit/index.ts, src/commands/sync/index.ts, src/commands/validate/index.ts, src/lib/utils/splog.ts, src/wrapper-classes/branch.ts
If there's no current checked out branch, rather than crashing noisily, catch this and handle it properly.
We do this by converting the `execSync` to find the current branch in a `gpExecSync` and then handle it locally at each callsite, surfacing the appropriate error.
=> [Sanity Check] No Current Branch

src/commands/original-commands/submit/index.ts, src/wrapper-classes/branch.ts
Allows us to later:
* decide whether we're creating or updating a PR
* show smart log without needing to hit the server
=> [Submit] Store returned PR info in branch metadata

src/actions/onto.ts, src/actions/repo_config.ts, src/actions/submit.ts, src/commands/repo-config-commands/repo_name.ts, src/commands/repo-config-commands/repo_owner.ts, src/commands/repo_config.ts, src/lib/utils/config.ts, src/lib/utils/index.ts
Adding commands to set/get fields in our repo config and then migrating our existing logic to use this same internal logic.
```
> lgp repo-config name
dummy
> lgp repo-config owner
nicholasyan
```
We can expand this next by making the trunk branches and the remote name (e.g. 'origin') customizable as well.
The payoff here is that creating a local repo config is now an opt-in action, avoiding the uncommitted changes issues we were seeing this morning. We always infer the fields unless the user chooses to set an override via `lgp repo-config <field> --set`.
This PR both adds + migrates things so it might be easier to review by reviewing each commit. (Each commit builds on its own.)
Also TODO here — tests.
=> [Repo Config] Add Repo Config Commands

src/actions/scope.ts, src/actions/submit.ts, src/actions/validate.ts, src/commands/stack-commands/submit.ts
Sharing a type for the scope arg so that we can seamlessly pass in the case where a command calls into a sub-command (e.g. submit calling validate).
=> Create Single Type for Scope Arguments

src/wrapper-classes/branch.ts
Right now `branchListFromShowRefOutput` stores hashes to branches in a record of string => string. This means that if multiple branch tips point to the same hash 1) whichever branch appears last in the ref output is saved as the definitive branch for that hash 2) all of the previous branches (which also point to that hash) are dropped.
This PR fixes the issue.
=> Fix branchListFromShowRefOutput to support multiple branches with same hash

src/wrapper-classes/git_stack_builder.ts
A branch may have multiple parents, so rather than just check whether the first one is trunk, check them all.
Along with the prior PR, this fixes the multiple-branches-same-commit issue that we ran into this morning.
=> Check all parents for trunk in fullStackFromBranch

src/lib/telemetry/profile.ts
Noticed this today when trying to track down telemetry for an issue — there's a type mismatch in our error telemetry which is causing us to lose traces. This PR fixes it.
Verified by causing error locally + watching local server.
=> Fix error telemetry

src/commands/log.ts
Now that Greg has introduced a proper error boundary, we *should* be throwing errors so that our telemetry captures it — rather than silencing them.
=> [Log] Surface errors

src/wrapper-classes/branch.ts
A few misc fixes:
Fix 1:
```
`git show-ref --heads | grep refs/heads/${this.name} -s | awk '{print $1}'`
```
* in `branchesWithSameCommit` we were using this command to find the ref for the given branch
* however, if the current branch was also a prefix for another branch's name (e.g. branch-a and branch-a1), this command would return multiple SHAs
* this would later get piped onto other commands which were expecting just 1 SHA
* fix: just re-use the existing `ref()` method as the source of truth (which correctly matches exactly the branch name)
Fix 2:
* in the case where no SHA was found for branches with the same commit, `...toString().trim().split("\n")` still returns an array `[ '' ]` with just the empty string
* this meant we were creating a bunch of branches with no name
* fix: we …
=> Fix mystery hash

src/commands/log-commands/long.ts
Adding `--branches` here instead of `--all` limits the search to show local branches (i.e. `refs/heads`) rather than everything in the `refs` folder.
=> [Log] Hide remote branches in log -c

src/actions/stacks.ts, test/commands/log/short.test.ts
Recreated in a test case a crash noticed by a user: https://screenplaydev.slack.com/archives/C028QNXTNBF/p1629219853474000?thread_ts=1629219370.473300&cid=C028QNXTNBF 
Then fixed the bug
=> fix(log_short): resolve complex repo crash state

src/commands/repo-commands/max_branch_length.ts, src/lib/config/repo_config.ts, src/wrapper-classes/branch.ts
**Context**
Earlier today, we ran into an issue where a branch was legitimately longer than our max cap right now: [context here](https://screenplaydev.slack.com/archives/C010GNVCUU9/p1629227572023100).
**This PR**
This PR adds a couple of things to fix this:
* Our max branch length is now stored in our repo config.
* We add a command to configure this max.
* We add a warning when we short-circuit a search due to the max.
* This is normally hidden since we normally silence the output of `gt stack validate`, but if we ever debug with a user and they run it, they'll be able to see the output.
Here it is in action:
=> [Repo Config] Allow max branch length to be configured

package.json, src/actions/submit.ts, src/lib/utils/pr_templates.ts, yarn.lock
If:
* we find a single PR template, when a user runs `gt submit` prefill the PR body with said template
* we find multiple PR templates, when a user runs `gt submit` prompt them to select the relevant template *for each PR* (the idea here that if there are multiple templates, it's likely that different PRs may require different templates)
* we find no PR templates, when a user runs `gt submit` do not prefill the body with anything
=> [Submit] Prefill PR body with PR template (if exists)

src/lib/config/exec_state_config.ts, src/lib/config/index.ts, src/lib/global-arguments/index.ts, src/lib/utils/splog.ts, src/wrapper-classes/branch.ts
This PR:
* Introduces a universal `--debug` flag for debug output.
* Adds an in-memory-only `execStateConfig` to allow us to configure various global settings (at this time just debug) during the invocation of the current CLI command.
* Leverages the above to output debug-only output when a short-circuited search for a parent/child of a branch is detected.
For `execStateConfig` I did consider just extending the pattern of using the `globalArgs` object, but I figured it'd be nice to have a separate object for:
* getters/setters
* settings that aren't set through global settings or have more complex logic than just global settings
* general modularity
Here is some sample output from this change: 
Note that I did my best to filter out duplicate warnings (only 1 warning per call of …
=> [Debug] Introduce 'debug' flag + add debug output for short-circuited parent/child searches

package.json, src/actions/submit.ts, src/commands/stack-commands/submit.ts, yarn.lock
Supporting this ultimate functionality:
```
gt stack submit 
gt stack submit --no-edit
gt stack submit --no-draft 
gt stack submit --no-interactive
```
Takeaways:
* editing your PR fields inline is by default on (but can be turned off with `--no-edit`)
* submitting as a draft is by default on (but can be turned off with `--no-draft`)
* the editing and draft flags operate completely independently
=> [Submit] Add 'draft' flag

src/actions/submit.ts, src/commands/stack-commands/submit.ts
**Context:**
The philosophy we've landed on is:
* for a vanilla command run, we prompt a user with maximal customizable functionality
* if a user ever wants to skip specifying these customizations, they can do so by passing in flags
In this PR we:
* make `draft` an optional argument
* prompt the user for the value if `draft` is undefined; otherwise we follow the `--draft` or `--no-draft` flags
* refactor the `draft`/`edit` logic
**Test Plan:**
Tested locally.
=> [Submit] Prompt user to confirm draft vs. publish

.CHANGELOG, package.json, src/wrapper-classes/branch.ts
**Details:**
Loading all refs into memory breaks if there are more than 6 million commits, and is very slow in general for large repos. The solution is to fetch subsets of refs for traversing git branch parents and children. In order to do this, Im dropping memoization for now because we're only loading subsets each time, but we could always bring back an advanced for later.
**Test Plan:**
Passes existing tests. I also profiled it against three repos:
cd graphite && gt ls = 4 sec before, 3.1 sec after
cd linux && gt ls =    25 sec before, 12 sec after
cd dagser && gt ls =   11 sec before, 5.5 sec after
=> perf(git_children): optimize ref traversal

.CHANGELOG, package.json, src/lib/utils/git_repo.ts, test/lib/scenes/index.ts, test/lib/scenes/public_repo_scene.ts, test/lib/utils/configure_test.ts, test/slow/large_repo.test.ts
**Context:**
We heard reports of hanging on the SmartThingsRepo. I've updated slow tests to clone generic repos and test them with differing timeouts. SmartThingsPublic appears slower than Dagster, but now we have coverage that we can ratchet down overtime.
=> ci(slow_tests): support testing public repos

.CHANGELOG, package.json, test/fast/commands/branch/branch_checkout.test.ts, test/fast/commands/log/short.test.ts
**Context:**
Keep things organized - these tests must have accidentally missed a previous reorg.
=> ci(move_files): move stragglers into organized folders

.CHANGELOG, package.json, src/lib/utils/trunk.ts, test/fast/commands/branch/branch_create.test.ts, test/fast/commands/repo/trunk.test.ts
**Context:**
Graphite has strange behavior for sibling branches. We currently dont detect trunk siblings - lets fix that.
**Test Plan:**
Add a unit test to ensure that an actionable Sibling Error is thrown if trunk has a sibling.
=> fix(trunk): disallow siblings on trunk branch

.github/workflows/premerge.yml, package.json
**Context:**
Unsurprisingly, slow tests are proving flaky. Start by breaking them out on CI and stop parallelizing them.
=> ci(slow_tests): break out in ci

src/actions/interactive_checkout.ts, src/actions/stacks.ts, src/commands/branch-commands/checkout.ts, src/commands/log-commands/short.ts, src/wrapper-classes/stack.ts
**Context:**
When we refactored the "Stacks" command, we never really split out the interactive checkout from log short. Lets do that now so that we can better iterate on log short
=> refactor(interactive_checkout): break out into another action

src/actions/log_short.ts, src/wrapper-classes/abstract_stack_builder.ts, src/wrapper-classes/git_stack_builder.ts, test/fast/commands/stack/clean.test.ts
**Context:**
This check is an unnecessary hit on performance for all stack / print operations. I needed to xit a clean test in order to make it, but Im going to refactor clean to use stack logic soon anyways - it already has known bugs.
=> perf(stack_builder): dont check merge base

src/actions/fix.ts, src/actions/log_short.ts, src/actions/onto.ts, src/lib/git-refs/branch_ref.ts, src/lib/git-refs/branch_relations.ts, src/lib/git-refs/cache.ts, src/lib/git-refs/index.ts, src/lib/utils/index.ts, src/wrapper-classes/abstract_stack_builder.ts, src/wrapper-classes/branch.ts, src/wrapper-classes/git_stack_builder.ts, test/fast/actions/validate_action.test.ts, test/fast/commands/stack/clean.test.ts, test/lib/utils/configure_test.ts
**Context:**
- centralize memoization logic into a cache class which can be cleared easily
- Clean up ref logic to use caching as well
In a future PR I want to move "allBranches" to this cache was well, but didn't want more scope creep than I already had here.
=> refactor(branch_refs): organize branch ref code

src/index.ts
=> chore(gp): start throwing errors on 'gp'

src/actions/commit_amend.ts, src/actions/commit_create.ts, src/actions/create_branch.ts, src/commands/branch-commands/next.ts, src/commands/branch-commands/prev.ts, src/commands/stack-commands/submit.ts, src/lib/config/exec_state_config.ts, src/lib/global-arguments/index.ts, src/lib/utils/splog.ts
Refactoring `globalArgs` to move it into the `execStateConfig` object with setters/getters. Moving forward, `execStateConfig` will hold all of the in-memory state for the current invoked CLI command.
=> Replace globalArgs with execStateConfig

src/lib/config/index.ts, src/lib/config/repo_config.ts, test/fast/commands/repo_config/repo_config.ts
Addressing the issue flagged [here](https://screenplaydev.slack.com/archives/C028QNXTNBF/p1629208065464800?thread_ts=1629207534.461600&cid=C028QNXTNBF).
Note sure where this comes from — the format of our repos for a regular clone, SSH key clone, or clone through the GitHub CLI — all include a `.git` suffix but this PR adds:
* support for this
* adds the offending URL to the error message so that it gets logged by us
* in the long run, we should also introduce a way to send additional info along with our logs (so that we don't have to add this to our error message itself)
=> Add ability to infer repo name/owner from additional origin URL type

src/actions/fix.ts, src/actions/log_short.ts, src/wrapper-classes/abstract_stack_builder.ts, src/wrapper-classes/git_stack_builder.ts, src/wrapper-classes/meta_stack_builder.ts, test/fast/wrapper-classes/stack_builder.test.ts
**Context:**
This started with me noticing a small bug in `gt ls`. I realized our implementation of `allStacksFromTrunk` was confusing and could be simplified into `allStacks`. I then moved the meta and git stack builder methods into the abstract class to further unify traversal logic - a lot of our edge bugs come from divergences in these stack traversals.
=> refactor(stacks): clean up duplicate implementations

src/lib/telemetry/profile.ts, test/lib/scenes/abstract_scene.ts
**Context:**
When debugging tests, we hide the stack traces. Let's change this suchg that when we use the DEBUG=true or run a command with the debug flag, we print error stack traces.
=> ci(debug): print stack traces when debug output enabled

src/actions/submit.ts
**Context:**
My suspicion is that this was the culprit for one of the submit 500s earlier today — I noticed that `title`, a required field was missing.
This PR prevents if from being undefined if the prompts library returns undefined.
**Test Plan:**
Could repro a 500 by giving prompts EOF on the `title` field; after the change, the server behaves correctly. I'll also reach out to the 500 user directly to verify the fix.
=> [Submit] Ensure 'title' field is defined

src/lib/errors/index.ts, src/lib/telemetry/index.ts, src/lib/telemetry/profile.ts, src/lib/telemetry/sigint_handler.ts
**Context:**
We have a current issue where we dont have any telemetry on when users are killing the CLI early. This means we're blind to hangs and other problems.
Let's handle the sigints and log to the server under a new error type.
example:
=> feat(telemetry): log when cli is killed

src/lib/telemetry/context.ts, src/lib/telemetry/index.ts, src/lib/telemetry/profile.ts
**Context:**
We originally ran these commands so that we could log the number of commits and branches a user has. For large repos, counting refs can take 5+ seconds. Some users with large repos are hitting this, so lets remove this logging in the name of perf.
=> perf(refs): dont fetch all refs for logging

src/lib/telemetry/profile.ts
**Context:**
I previously assumed that logging the error would also print the trace. It didn't, so Im correcting this attempt.
=> fix(debug_output): correctly log error trace

src/actions/sync.ts, src/commands/repo-commands/repo_sync.ts, test/fast/commands/repo/sync.test.ts
**Context:**
Refactor clean into `repo sync` because the command operates on all branches within the repo, and we plan to also have the command help clean metadata from the .git/refs/branch-metadata folder.
=> refactor(clean): rename to repo sync

src/commands/branch-commands/rename.ts, src/wrapper-classes/index.ts, src/wrapper-classes/metadata_ref.ts
**Context:**
We now have multiple commands that interact with metadata refs - sync, rename, etc. Lets move into a wrapper class to handle better.
=> util(metadataRef): start pattern of metadata_ref wrapper class

src/commands/stack-commands/test.ts
**Context:**
I frequently want to run a command like `yarn test-fast` for each branch in by stack while debugging. This PR adds the command:
```
gt stack test <command>
```
Which iteratively checks out each branch in the stack and runs any command on it. In the future, I'd like to update it for bisecting, but this is fine for now.
=> feat(stack_test): new command for testing

src/wrapper-classes/branch.ts
**Context:**
`getAllBranchesWithoutParents` is broken; this PR fixes it.
As titled.
**Test Plan:**
Originally noticed that branches were appearing multiples times in the output of `gt log`. This PR eliminates the problem for me locally.
=> Fix branches without parents method

src/actions/print_stack.ts, src/wrapper-classes/branch.ts
**Context:**
Sometimes it's helpful to see the commit info as well.
**Test Plan:**
| Before | After |
| -- | -- |
| <img width="535" alt="Screen Shot 2021-08-30 at 4 44 39 PM" src="https://user-images.githubusercontent.com/9063972/131410443-b6e452b6-afcd-42ec-87df-941bd9dca853.png"> | <img width="548" alt="Screen Shot 2021-08-30 at 4 44 10 PM" src="https://user-images.githubusercontent.com/9063972/131410450-2f863326-2d5b-44f4-9da6-f8a44eda5aac.png"> |
=> [Log] Show commit info per branch

src/lib/config/repo_config.ts, src/lib/telemetry/fetch_pr_info.ts
**Context:**
Now that we'll be making background fetches for PR information in log, we want to make sure to rate limit these so that users don't run into GitHub API limits.
This PR sets the limit to a max of 1 PR info request per minute. In reality, this will be lower because these requests are only kicked off when a user runs a Graphite command. As a result, the real consumption rate here is the time between Graphite command invocations or increments of one minute — whichever is greater.
**Test Plan:**
Printed if in the rate limit case; verified it was triggering locally.
=> [Log] Rate limit API requests

src/lib/utils/trunk.ts, src/wrapper-classes/branch.ts, src/wrapper-classes/git_stack_builder.ts, test/fast/commands/log/short.test.ts, test/fast/commands/repo/sync.test.ts, test/fast/commands/repo/trunk.test.ts, test/fast/wrapper-classes/branch.test.ts, test/fast/wrapper-classes/stack_builder.test.ts
**Context:**
Using meta to break ties in sibling branches is causing more problems than we'd like. Revert for now while we test alternative solutions.
=> revert(siblings): undo tie breaking logic for git traversal

src/commands/branch-commands/submit.ts, src/commands/downstack-commands/submit.ts, src/commands/shared-commands/submit.ts, src/commands/stack-commands/submit.ts, src/commands/upstack-commands/submit.ts
**Context:**
As titled.
Shares everything but description (command-specific) between the upstack, downstack, stack, and branch submit commands.
**Test Plan:**
yarn build
=> [Submit] Share boilerplate between submit commands

src/commands/feedback-commands/debug_context.ts, src/lib/debug-context/index.ts, src/lib/git-refs/branch_ref.ts, src/lib/git-refs/branch_relations.ts, src/lib/utils/git_repo.ts, test/fast/commands/feedback/debug_context.test.ts
**Context:**
Create a command for printing debug-context, as well as recreating that debug state in a tmp dir. This will be used for recreating buggy state reported by users.
example of captured output:
```
graphite-cli on  gf--feat_feedback_include_optional_debug [$] is 📦 v0.13.1 via ⬢ v15.14.0 took 6s 
➜ gt feedback debug-context
{
"refTree": {
"238b0c7d213c069298ab999b7e49ad95efa01e47": [
"40e3da7d76e361aef643690257c8d6b34893b31a"
],
"40e3da7d76e361aef643690257c8d6b34893b31a": [
"62dee0ad44dfe5acf27b028ca24f7105c5db24f7"
],
"62dee0ad44dfe5acf27b028ca24f7105c5db24f7": [
"7443950555f28e449c21b75ea80ed8c5cebe4461"
],
"b7105dfa9d8d4ff2a18343b79c76e6767e500b0c": [
"7443950555f28e449c21b75ea80ed8c5cebe4461"
],
"4ba51fa3fc886204c3e07f804f34c2369051033d": [ …
```
=> feat(state_capture): command to summarize repo state

src/lib/config/repo_config.ts, src/lib/git-refs/branch_ref.ts, test/fast/commands/repo/trunk.test.ts
**Context:**
A user reported a bug where their ignored trailing branch caught up to main and started causing sibling errors.
Update the code to more correcly ignore "ignored-branches", including when checking for sibling branches.
=> fix(trunk): ignore sibling branches correctly

src/actions/interactive_checkout.ts, src/lib/telemetry/profile.ts
**Context:**
I noticed that cntr-c from `gt bco` gave a nasty error message, but behaved correctly. This PR tones down logging when cancelling out of a command.
=> fix(cancel): improve logging when killing during prompt

.gitignore, src/actions/create_branch.ts, src/commands/branch-commands/create.ts, src/lib/preconditions/index.ts, src/lib/utils/exec_sync.ts, src/lib/utils/git_repo.ts, src/lib/utils/index.ts, src/lib/utils/unstaged_changes.ts, test/fast/commands/branch/branch_create.test.ts
**Context:** -a flag (all) should `git add --all` before making a possible commit on the new branch. 
1. Changes to support -a flag on `branch create`
2. Tests to ensure that changes work as expected
3. Helper functions and utils for tests
**Test Plan:**
Automated: `yarn test-fast`
Manual: 
1. Make changes. Do not add or commit those changes. 
2. Use `git status -u` these changes should appear as untracked files.
3. Use `gt branch create -m "<branch name>" -a`. 
4. Check that all the changes that were untracked before were committed into the newly created branch above.
=> [SP-1452] add all on branch create

package.json, src/commands/branch-commands/pr.ts, src/lib/requests/fetch_pr_info.ts, src/lib/sync/pr_info.ts, src/wrapper-classes/metadata_ref.ts, yarn.lock
**Context:**
Multiple users in the past week have ended up in a state where they submitted a PR without Graphite and then later worked on a stack with Graphite — and wanted to let Graphite know about the existing PR.
This PR adds a command, `gt branch set-pr`, that allows users to manually link a given branch to a PR. The up-level here is to bake functionality into the sync command that automatically links outstanding PRs to branches given their branch names, but I'm adding this as a temporary stopgap while I go and implement that.
One corner case introduced here — users can now link local branches to PRs with a different head ref name. While this made sense in Phabricator land, it makes little sense here now since 1) the local branch is being pushed to a …
=> Add command to link branches to PRs

package.json, src/lib/sync/pr_info.ts, yarn.lock
**Context:**
After modifying our server endpoint to be able to query PRs via their name (in addition to their associated PR number), I think we're going to want to migrate the CLI to use PR names as the source of truth. This allows us to query for all PRs, regardless of whether Graphite previously knew that a PR existed for the branch.
This PR migrates our PR syncing logic to use this new slice of the endpoint. 
This change does incur more API requests so my current thinking is that:
* the background fetch that we do a max of every minute will still only query for updated information about PRs Graphite already knows about (so no change in behavior)
* we'll query for all PRs 1) when a user runs submit and 2) when a user runs repo sync
**Test Plan:**
Tested …
=> [PR Info] Sync PR info via head ref, not PR number

src/actions/print_stack.ts, src/commands/branch-commands/pr.ts
**Context:**
See previous PR.
Now that we don't need a PR number to find a pull request, we can also make our branch sync-pr command more developer friendly. You can just run it, force-fetching (and updating) any PR information about the current branch — without needing to supply a PR number.
I've also edited the return format to print out the linked PR in the same format as our log output.
**Test Plan:**
Unlinked/linked a PR, attempted to link a PR without an associated branch.
=> [Sync PR] Update branch sync-pr to no longer need PR number

src/actions/sync.ts, src/commands/repo-commands/repo_sync.ts
**Context:**
As titled.
Adding options to repo sync to allow users (or tests) to skip the delete and/or resubmission portions of the command. This will be used in tests in the next PR.
**Test Plan:**
yarn build
=> [Repo Sync] Add options to skip delete or resubmit

src/actions/sync.ts
**Context:**
Noticed repo sync was trying to resubmit trunk and branches without bases in my local test repo, causing errors.
Filter these out.
**Test Plan:**
Running repo sync in my local repo ignores these branches now.
=> [Repo Sync] Don't resubmit trunk or branches without bases

src/actions/sync.ts
**Context:**
https://linear.app/screenplay/issue/SP-1717/[repo-sync]-dont-change-the-base-branch-of-the-pr-if-it-was-the-one
These *should* be filtered out before this point by other parts of the command, but let's add an extra sanity check to make doubly sure.
**Test Plan:**
yarn build
=> [Repo Sync] Double-check that we're not resubmitting merged or closed PRs

src/actions/submit.ts, src/actions/sync.ts
**Context:**
Refactoring to share more logic with the submit command. Introducing a single, shared `submitBranches` command.
**Test Plan:**
`repo sync`, verify that it resubmits branches with changed bases correctly
=> [Repo Sync] Refactor re-submit logic

src/actions/sync.ts, src/commands/repo-commands/repo_sync.ts
**Context:**
When the user runs `repo sync`, we can also upsell them on fixing any dangling branches found in their repo. This also then allows us to check whether these dangling branches should be deleted or re-submitted.
Adds a step to repo sync to flag dangling branches and suggest fixing them back onto trunk.
**Test Plan:**
tested locally
=> [Repo Sync] Catch dangling branches

src/actions/submit.ts
**Context:**
We see a fair number of submit errors where submit has been called on a PR that was already merged.
If we know a PR has already been merged (e.g. through background updates or a call to repo sync), we skip it when the user calls submit. 
Note that we don't skip PRs which were just closed (without merging).
**Test Plan:**
yarn build
=> [Submit] Ignore already-merged branches

src/lib/sync/pr_info.ts
**Context:**
Addressing some feedback that after our most recent changes to repo sync, that one user's trunk branch was pulling in PR info and was showing as "abandoned." My theory here is that the trunk branch has a long-lived trailing branch and that at some point, a PR that merged trunk into the trailing branch was abandoned.
Special casing by a single branch (even if it is trunk) doesn't feel great, but I couldn't think of a better solution here. So in this PR, we just make sure that when we're fetching PR info from our PR info endpoint, we don't request any info for trunk.
**Test Plan:**
yarn build
=> [PR Info] Don't fetch PR info for trunk

src/commands/branch-commands/sync.ts, src/wrapper-classes/branch.ts
**Context:**
In #340 we added behavior to not sync PR info for trunk to fix the issue forward for the user who saw a "abandoned" trunk PR. I also want to give them a way to reset the PR info for their branch.
This PR introduces a `--reset` option (open to naming suggestions here) which clears the current PR info for a branch.
Note that we have lots of ways to re-fetch PR info for a branch, but this currently works nicely with them all:
* we fetch PR info in the background, but only do so if we know that the branch already was associated with a PR
* in `repo sync`, we fetch PR info for all branches — but in the user's case, we've special-cased trunk to rule it out
* note that this does mean that you can reset PR info, run `repo sync`, and see the PR info …
=> [Sync] Add --reset to remove branch PR info

src/commands/branch-commands/parent.ts, src/wrapper-classes/branch.ts
**Context:**
Earlier today, with the new logic in `repo sync` to fix dangling branches, I accidentally affixed a branch I wanted ignored to trunk.
I think there's 2 fixes necessary here:
* add a command that can reset a parent to `undefined`
* add a larger suite of options when fixing dangling branches
This PR addresses the first. The next PR addresses the second.
**Test Plan:**
reset a branch's parent locally; verified through `gt branch parent`
=> [Branch] Add parent --reset command

src/actions/sync.ts, src/lib/config/repo_config.ts
**Context:**
Earlier today, with the new logic in `repo sync` to fix dangling branches, I accidentally affixed a branch I wanted ignored to trunk.
I think there's 2 fixes necessary here:
* add a command that can reset a parent to `undefined`
* add a larger suite of options when fixing dangling branches
This PR addresses the second. (The previous PR addressed the first.)
**Test Plan:**
=> [Dangling Branches] Add more fix options

src/commands/autocomplete.ts, src/commands/branch_autocomplete.ts
This PR supports git branch autocomplete for our branch commands:
* `gt branch checkout --branch`
* `gt upstack onto`
We take advantage of the yargs [`completion` API](https://yargs.js.org/docs/#api-reference-completioncmd-description-fn) which creates a command that when run will spit out some bash to add to your `.bashrc`/`.zshrc`/`.zsh_profile` to hook into custom autocomplete logic.
This API isn't perfect — it looks like you have to specify the completion logic in one place, away from where the commands are defined so I'd imagine this is very brittle — but it does give us a good starting point.
@gregorymfoster also mentioned that there was a way to automatically run this script and add it to the relevant file in Homebrew, but I'll take a look into …
=> Branch autocomplete MVP

src/actions/sync.ts, src/commands/branch_autocomplete.ts
**Context:**
Right now, `repo sync` runs through a stack and:
* checks if the current branch has been merged and can be deleted
* if it should be deleted, upstacks the remaining branches
* deletes the branch
This is inefficient if multiple branches in a stack have already been merged since we do some extra upstacking — which also poses the risk of requiring the user to resolve merge conflicts for branches that are going to be deleted anyway.
This PR changes our logic to greedily delete branches, upstacking only when we reach a branch that should not be deleted.
**Test Plan:**
`repo sync` tests; tested the happy path with a stack with 3 PRs with the bottom 2 already merged in, verifying that both branches were deleted *and then* the upstack was kicked off
=> [Repo Sync] Greedily delete, then upstack

src/commands/feedback-commands/debug_context.ts
Adds an option to read the debug context blob directly from a filepath.
**Test Plan:**
tested locally
=> [Debug Context] Read from file, rather than plain string

src/lib/utils/index.ts
Easy, as titled.
We export the rest of the methods in the file so doing for `logDebug` as well.
=> Export logDebug in lib/utils

src/actions/print_stack.ts, src/commands/branch-commands/sync.ts, src/commands/log-commands/default.ts
**Context:**
Today, log doesn't handle merges well.
Consider the following case:
* we have branch A, off of which exist branches B and C
* we merge branch B back into C
We get this triangle case:
```
C
|\
| B
|/
A
```
Right now, we print out the log by doing a DFS which in the above case prints C twice: once when we process the subtree of A and another time when we process the subtree of B.
This PR adds a temporary stop-gap in the `printStack` method to keep track of visited nodes and skip those.
Note that a larger holistic fix is needed for the CLI, but this should do for the near term.
**Test Plan:**
pre-existing tests pass; Tomas's log no longer infinitely prints
=> [Log] Stopgap to handle merges

src/lib/utils/git_repo.ts, src/wrapper-classes/abstract_stack_builder.ts, src/wrapper-classes/branch.ts, test/fast/wrapper-classes/stack_builder.test.ts
**Context:**
This follows the same strategy as the previous PR (#354), but adds the logic to our abstract stack builder.
Note that we need to add this in 2 places since our log logic doesn't use our abstract stack building logic yet; that's a task that I'll take on at a later date.
This change is a lot more ugly since we need to worry more about correctness here and make sure that we deterministically determine which branches to short-circuit. This tech debt highlights to me that we need a proper fix to merges sooner rather than later.
**Test Plan:**
existing tests still pass, added a new test
=> [Stack Builder] Merge stopgap

src/actions/sync.ts, src/lib/debug-context/index.ts
**Context:**
Right now, in `repo sync`, we delete branches in a 3-step process:
* run through and find all of the branches we want to delete
* then go and upstack all of their children
* finally, go through and actually delete all the branches that can now be deleted
This is usually fine but is frustrating if you have lots and lots of stale branches -- you don't get any feedback from the command and if you kill it before step 3, you lose all of the work it just did. (Was running it on a repo with 300 stale branches today and it was taking on the order of > 5 minutes so it'd be easy to just kill it, thinking it was hanging.)
Since we want to encourage users to cull these large sets of stale branches, we should strive to make this as easy as possible.
This …
=> [Repo Sync] Eagerly delete branches during repo sync

src/actions/sync.ts, src/commands/repo-commands/repo_sync.ts
**Context:**
In the 300 stale branch case, it's still agonizing to see it chug along without any idea of how long the overall command will take.
This PR adds a progress indicator. The progress indicator isn't perfect, especially since we don't want to go through every branch and determine whether it was merged -- that'd be far to slow. Instead, we estimate that the user's stacks are fairly evenly distributed and calculate progress based on the stack base index that we've reached in the DFS.
Since this is far from perfect, this flag is opt-in. The idea is that we just tell folks to turn it on if they're doing a `repo sync` that is deleting a particularly high number of stale branches. 
**Test Plan:**
tested locally
=> [Repo Sync] Add option to show deletion progress

src/actions/clean_branches.ts, src/actions/fix_dangling_branches.ts, src/actions/sync.ts, src/commands/repo-commands/fix.ts
**Context:**
With the prior PRs, we now have a good way to aid users in removing stale branches — even in large cases.
The payoff is a new fix command which we can provide users when they're running into performance issues.
This PR introduces said command, breaking out the logic in `repo sync` into shared code.
The fix command for now:
* checks if there are dangling branches (and guides the user with fixing them)
* asks the user if they'd like to remove their stale branches, one-by-one
**Test Plan:**
yarn build; ran fix in Jonas's debug context
=> [Repo Fix] New commmand

src/actions/init.ts, src/lib/telemetry/profile.ts, src/wrapper-classes/branch.ts
**Context:**
Right now, when users run Graphite in an empty repo, they receive a cryptic message to set their trunk to `[object Object]`. Digging in, this is the result of multiple bugs:
1. When a branch new repo is initialized, it has no branches: https://newbedev.com/git-branch-not-returning-any-results. We could try to dig in harder to figure what the orphan branch is, but Googling around there's no trivial way to do this, and I worry about this causing further breakages as we're going against the grain here. Even git gives an error when you try to find a branch in an empty repo:
```
~/test  git init                                                                               ✔
hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to …
```
=> [Repo Init] Handle empty repo properly

src/actions/print_stack.ts, src/actions/submit.ts, src/wrapper-classes/commit.ts, test/fast/actions/submit_action.test.ts
This PR allows the CLI to parse the submit message from a multi-line commit.
(new to me) Git itself parses its commit messages with a 'subject' and a 'body'. So far, our commit message logic has just extracted the 'subject' (aka the title) of the commit.
This PR 1) adds support for grabbing the 'body' and 2) hooks that up to our submit logic.
This PR was authored and submitted with this new functionality.
=> [Submit] Infer body from commit message

src/actions/commit_create.ts, src/commands/commit-commands/create.ts
Some users have requested the ability to run `gt commit create` without specifying a message inline (instead launching their default editor to write the message).
This PR adds that logic.
Note that I added some code duplication given that I don't expect this code to be updated often and it makes things a bit more clear; the alternative was a bunch of ternaries around the message argument.
=> [Commit Create] Allow editing without -m

src/actions/init.ts, src/lib/config/repo_config.ts, src/lib/requests/fetch_pr_info.ts, src/lib/telemetry/profile.ts, src/lib/telemetry/upgrade_prompt.ts
**Context:**
The welcome message is broken right now because:
- we show the message if the repo config file does not exist
- we have multiple background commands that race and write repo config
This PR fixes the message by:
- standardizing the way we check whether Graphite has been initialized (in a single method)
- having these other background fetches only fetch if Graphite has been initialized
**Test Plan:**
welcome message is now shown in an empty repo
=> Fix welcome message

src/actions/fix.ts
Addressing some perf issues, anywhere where we're just doing read operations in stack fix (e.g. determining what the meta and git stacks look like), we can use memoized data.
This PR turns those settings on.
The operations we need to be careful on are the regen/upstack side of things, but all of these lines should avoid that since we cleanly 1) determine the shape of the stacks 2) ask for input 3) *then* take the necessary action.
=> [Stack Fix] Memoize stack lookups

src/wrapper-classes/abstract_stack_builder.ts
As titled; we want to make sure that if the stack calculation is memoized, the branches that its using for intermediate calculations are also taking advantage of this setting and using memoized settings themselves.
=> [Perf] Memoize branches passed to memoized stacks

src/actions/stack_traversal.ts, src/commands/branch-commands/top.ts
**Context:**
Adding support for `gt branch top`
**Test Plan:**
Manual testing. Following commands should work:
`gt branch top` should take you the bottom-most, non-trunk branch on the stack. 
Interactive mode is supported since a branch can have multiple children. Upon selecting a child branch, the command will traverse to the top of the chosen stack.
=> feat(branch): add support for gt branch top

src/actions/commit_create.ts, test/fast/commands/commit/create.test.ts
Forgot to add quotes around the commit message; adding to fix multi-word commit messages.
=> [Commit Create] Fix

src/actions/create_branch.ts, src/wrapper-classes/branch.ts, test/fast/commands/branch/branch_create.test.ts
**Context:**
Users were hitting an issue where:
1. they created a branch and submitted it
2. they deleted the branch (`git branch -D`)
3. they created a new branch of the same name -- and Graphite incorrectly connected the old PR to said branch
The root cause here is that the Graphite metadata for the branch isn't being deleted between steps 2 and 3 (the only command that deletes metadata today is `gt repo sync`).
This PR changes create branch to clear any branch metadata before setting the new branch metadata.
**Test Plan:**
test included
=> [Branch Create] Clear any previous, stale metadata

src/actions/submit/pr_body.ts, src/actions/submit/pr_title.ts, src/actions/submit/submit.ts, src/wrapper-classes/branch.ts, src/wrapper-classes/metadata_ref.ts
**Context:**
Right now, if submit crashes, we don't save any of the title or body information you may have entered (which may be paragraphs in the worst case).
This is a bad experience.
This PR saves your entered title and body, immediately after you enter each, on the branch metadata.
**Test Plan:**
killed submit after entering title and body; next invocation had both prepopulated
=> [Submit] Save state if submit exits early

package.json, src/actions/fix.ts, src/actions/submit/submit.ts, src/actions/validate.ts, src/commands/autocomplete.ts, src/commands/branch-commands/rename.ts, src/commands/repo-commands/ignored_branches.ts, src/lib/errors/index.ts, src/lib/telemetry/survey.ts, src/lib/utils/single_commit.ts, src/wrapper-classes/git_stack_builder.ts, src/wrapper-classes/index.ts, test/fast/actions/submit_action.test.ts, test/fast/commands/branch/branch_create.test.ts, test/fast/commands/branch/branch_delete.test.ts, test/fast/commands/stack/fix.test.ts, test/fast/wrapper-classes/stack_builder.test.ts, yarn.lock
Context:
The following stack is going to introduce a lot of the CLI logic that we'll use to query our users for feedback on the CLI.
Note that none of these tests will pass until I land corresponding changes to graphite-cli-routes.
This PR adds the logic that controls when the survey is shown to the user. After this change, during submit invocations, while posting the PRs, we simultaneously ask the server for the messages and questions we should show in our survey (and therefore, implicitly, whether a survey should be shown at all).
**Test Plan:**
yarn build, ran locally
=> [Survey] Only show survey when server tells CLI to

src/lib/telemetry/tracer.ts
**Context:**
Right now, Datadog doesn't aggregate our traces.
After this PR, the traces accurately depict parent-child relationships (see attached photo), but all of the children are inexplicably located at the end of the parent timespan. I timeboxed an investigation into this last week and couldn't find anything, but putting up this fix as it's a net win.
**Test Plan:**
=> Fix parents in trace flame graphs

src/actions/commit_amend.ts, src/actions/commit_create.ts, src/actions/fix.ts, src/actions/onto.ts, src/commands/stack-commands/fix.ts, src/lib/config/merge_conflict_callstack_config.ts
**Context:**
Our overall goal in this stack of PRs is to introduce a gt continue command which can be a Graphite replacement for git rebase --continue when a merge conflict interrupts the execution of a Graphite command.
We plan to do this by essentially capturing the callstack in a very lightweight matter at the time when we detect the merge conflict, persisting this, and then re-reading this config when the user runs gt continue.
This PR persists the interrupted callstack for any method that calls into the fix action.
Test Plan:
yarn build for now, more complex functionality and tests built atop this upstack
=> [Continue] Persist callstack on merge conflict in stack fix

src/actions/commit_amend.ts, src/commands/continue.ts, src/commands/stack-commands/fix.ts, src/lib/config/merge_conflict_callstack_config.ts, test/fast/commands/commit/amend_continue.test.ts
**Context:**
Now that we've walked through the setup for one command — `gt stack fix` — we're going to quickly run through the other callsites where a merge conflict can interrupt Graphite and a callstack needs to be persisted/continued.
These locations are:
* anywhere a stack fix is invoked under the hood
* commit amend 
* commit create
* upstack onto
* anywhere an upstack onto is invoked under the hood
* upstack onto 
* repo fix (during branch deletion)
* repo sync (during branch deletion)
This PR adds the new functionality for `gt commit amend` and adds a relevant test as well.
**Test Plan:**
test included
=> [Continue] Support commit amend

src/actions/submit/pr_body.ts, src/actions/submit/submit.ts, src/lib/config/user_config.ts, src/lib/utils/default_editor.ts
**Context:**
Currently, the way we choose editor preference is pretty opaque. Prompt the user to set the editor preference if not set on submit. If the user chooses to not set it, then nano is saved as the preference and user will not be prompted again.
1. Save editor preference in user config.
2. Prompt user to set the preference (if unset) on submit.
3. Default to nano.
**Test Plan:**
Tested manually.
=>  Set editor preference if not set, on submit

src/commands/user-commands/editor.ts, src/lib/utils/default_editor.ts, test/fast/commands/user_config/editor.test.ts
**Context:**
Since we are now saving editor preferences in user config, allow `gt user editor` to change them.
**Test Plan:**
Tested manually.
=> Allow `gt user editor` to set/unset editor pref

src/commands/feedback-commands/default.ts, src/commands/feedback.ts, yarn.lock
- Allow the --debugContext to submit debug context automatically to slack
- Disable help on failure because for some reason help is not being read correctly.
**Context:**
`gt feedback` on failure displays incorrect help menu. 
**Test Plan:**
Tested manually
=> fix(feedback): allow sending debug-context, disable help for now

src/lib/utils/committer_date.ts, src/wrapper-classes/branch.ts, src/wrapper-classes/commit.ts, test/fast/commands/log/short.test.ts
**Context:**
git log will crash if there's a branch and a file with the same name
Fix all instances of git log
**Test Plan:**
Added a test for the git log used in `gt log`
There's another one used in `gt log short` which I tested manually, but had trouble adding a unit test for - as it only appeared when there were multiple untracked stacks (only used in the sorting of stacks).
=> Fix git log for cases where branch name matches an existing file

src/commands/dev-commands/stack.ts, src/commands/dev.ts
I find myself often needing to create a test stack. I used to do this manually but have been hacking the demo command to do this for some time now.
I figured I might as well commit this. The command is hidden and can be invoked via `gt dev create-stack` or `gt dev cs` for short.
=> feat: dev command to create test stack

src/actions/validate.ts
**Context:**
Noticed that `gt ds s` was often just not working for me — it'd incorrectly say that there were no branches to update.
Traced the cause to stack validate.
A change introduced a while back directly modifies the arguments supplied to stack validate (clearing the stack's parent/children), which in turn messes with the submit args.
**Test Plan:**
`gt ds s` works again
=> fix: stack validate mutates args

src/actions/commit_amend.ts, src/actions/commit_create.ts, src/actions/fix.ts, src/actions/onto.ts, src/actions/sync.ts, src/lib/utils/index.ts
**Context:**
When editing gitignore on one branch, you end up with untracked files on other simultaneous branches.
Git itself lets you do checkouts with existing untracked files unless they would be clobbered by checkout. Allow this to work the same way.
**Test Plan:**
Confirmed manually that `git status -uno` does what we want - so use that helper instead.
=> Allow gt repo sync with untracked files

scripts/installation/install_dev.sh, scripts/installation/install_nightly.sh, scripts/installation/install_stable.sh, scripts/installation/uninstall.sh, src/actions/clean_branches.ts, src/actions/onto/current_branch_onto.ts, src/actions/onto/stack_onto.ts, src/commands/continue.ts, src/commands/upstack-commands/onto.ts
For the upcoming `stack edit`, we'll need to expose the inner method on `onto`, such that we can use it to re-order stacks.
=> refactor(onto): expose onto method

src/actions/edit/create_stack_edit_file.ts, src/actions/edit/edit_downstack.ts, src/commands/downstack-commands/edit.ts, test/fast/commands/downstack/edit.test.ts
Downstack edit will need some solid unit testing in order to verify edge cases. Start a simple pattern with a sanity test and a hidden arg for input files to bypass prompting.
=> test(edit): add first sanity check to downstack edit

src/actions/edit/create_stack_edit_file.ts, src/actions/edit/parse_stack_edit_file.ts, test/fast/commands/downstack/edit.test.ts
**Context:**
Xiulung gave great feedback that we should order the edit list to show trunk at the bottom in order to better match the verbage of "upstack" and "downstack".
=> feat(edit): invert stack order in edit file

src/actions/edit/create_stack_edit_file.ts, src/actions/edit/parse_stack_edit_file.ts, test/fast/commands/downstack/edit.test.ts
**Context:**
Integrate feedback from Tomas, such that we show the trunk branch commented out so users get orientated, but dont try to rearrange the trunk in the stack.
=> feat(edit): show trunk branch as comment

src/actions/create_branch.ts, src/actions/print_stack.ts, src/lib/utils/single_commit.ts, src/wrapper-classes/branch.ts, test/fast/commands/log/short.test.ts, test/fast/wrapper-classes/stack_builder.test.ts
**Context:**
We've heard from users a desire to be able to create a branch without committing, and not get an error.
This change enables that workflow by having branch create support always making a commit, sometimes empty if no changes are staged. This does not mean that graphite supports two branches pointing to the same commit, like what happens if you merge a branch into another. However, it does enable the common case.
I considered adding work to try and delete empty commits when possible, but based on research I think git already does that for us when operations like rebases happen. All tests are still passing as expected, so I figure we can try this for now.
=> feat(create_branch): empty commits

src/actions/create_branch.ts, src/actions/print_stack.ts, src/lib/utils/single_commit.ts, src/wrapper-classes/branch.ts, test/fast/actions/submit_action.test.ts, test/fast/commands/branch/branch_create.test.ts, test/fast/commands/branch/branch_delete.test.ts, test/fast/commands/log/short.test.ts, test/fast/wrapper-classes/branch.test.ts, test/fast/yargs/two_letter_shortcuts.test.ts
**Context:**
When we create empty commits, they currently get a message of "undefined". Let's fix that such:
* if the user passes a -m, we use the message
* Otherwise, we show the standard commit message prompt and add comments to explain why the empty commit is coming into existance.
=> fix(empty_branch): better commit message

package.json
**Context:**
necessary so we can start publishing the cli on npm
=> chore(package): remove private

src/actions/init.ts, src/commands/repo-commands/ignored_branches.ts, src/commands/repo-commands/max_branch_length.ts, src/commands/repo-commands/max_days_behind_trunk.ts, src/commands/repo-commands/max_stacks_behind_trunk.ts, src/commands/repo-commands/repo_name.ts, src/commands/repo-commands/repo_owner.ts, src/lib/config/compose_config.ts, src/lib/config/index.ts, src/lib/config/repo_config.ts, src/lib/context/context.ts, src/lib/debug-context/index.ts, src/lib/requests/fetch_pr_info.ts, src/lib/telemetry/profile.ts, src/lib/utils/trunk.ts, test/fast/commands/repo/ignored_branches.test.ts, test/fast/commands/repo/stack_settings.test.ts, test/fast/commands/repo/sync.test.ts
**Context:**
We've been using a bit of a bad pattern for our various CLI config files - global class based singletons. Among other issues, these create flaky CI failures when running parallelized tests.
This change:
* Starts a pattern of using functional coding for configs over classes
* Set up room to override config location in future (will be useful for parallel CI tests)
* Starts angling towards a pattern of factory rather than global singleton, which we'll take advantage of upstack.
=> refactor(repo_config): use injection

.github/workflows/premerge.yml, src/lib/config/compose_config.ts, src/lib/utils/git_repo.ts, test/fast/commands/repo_config/repo_config.ts
**Context:**
Fix a user reported bug where the repo config wasnt readable from subdirs of a repo. Add a regression test as well.
=> fix(config): read configs from subdirs

src/lib/config/survey_config.ts, src/lib/telemetry/survey/post_survey.ts, src/lib/telemetry/survey/survey.ts
**Context:**
Using the pattern started with RepoConfig, move SurveyConfig to a functional, retype based configuration. Upstack, we'll drop the global and move into the TContext object.
=> refactor(survey_config): dont use global

src/actions/submit/submit.ts, src/index.ts, src/lib/config/survey_config.ts, src/lib/context/context.ts, src/lib/telemetry/profile.ts, src/lib/telemetry/survey/post_survey.ts, src/lib/telemetry/survey/survey.ts
**Context:**
Im working through all the configuration files in the CLI and moving them to an injected context object rather than having them globally accessed. This change in pattern improves testability and reduces race conditions.
=> refactor(survey): move config to context

.eslintrc
**Context:**
Copy from server's eslint pattern. https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/unambiguous.md
=> lint(imports): unambigious rule

src/actions/create_branch.ts
Updating copy to make it more clear to the user why Graphite adds an empty commit when creating a branch with no staged changes.
=> Update copy in create_branch.ts

src/actions/commit_amend.ts, test/fast/commands/commit/amend.test.ts
**Context:**
Amend does not pass commit message with quotes. This is similar to https://github.com/withgraphite/graphite-cli/pull/375.
Add quotes around commit message passed to `gt commit amend`
**Test Plan:**
Added test based on https://github.com/withgraphite/graphite-cli/pull/375
=> Update amend to pass message with quotes

src/lib/utils/commit.ts
**Context:**
fish users should be able to use backticks in commit string (parity with git)
**Test Plan:**
tested using fish as shell
=> fix: allow backticks in commit title

src/lib/config/compose_config.ts
**Context:**
If the config gets malformed, we're currently logging to many details - this is biting users around malformed merge_confict_continue configs. We should fix the root, but until then, let's reduce the scary messaging.
=> fix(retype): dont log errors

src/actions/submit/submit.ts, src/lib/sync/pr_info.ts
This brings us back to the old state of the world where we only sync branches that have been submitted on this machine.  This prevents the issue where branches with the same name as closed PRs would be deleted inadvertently and toward the world where graphite only operates on branches it knows about.
The future direction here is that this will correctly sync branches both submitted and retrieved with `gt get`
=> fix: use pr number as source of truth for sync instead of branch name

src/actions/clean_branches.ts, src/lib/utils/detect_staged_changes.ts
User flagged a hanging issue when `git config diff.external`, which this flag skips, is set.
=> fix: add --no-ext-diff option to git diff invocations

src/lib/utils/detect_unsubmitted_changes.ts
was getting
```
fatal: ambiguous argument 'a': both revision and filename
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```
when trying to `gt ss` a branch sharing name w/ a file (for testing)
=> fix: issue with submit when filename and branch conflict

src/actions/delete_branch.ts, src/actions/log_short.ts, src/commands/branch-commands/delete.ts, test/fast/commands/branch/branch_delete.test.ts, test/lib/utils/fake_squash_and_merge.ts
BEFORE:
```
error: The branch 'hello' is not fully merged.
If you are sure you want to delete it, run 'git branch -D hello'.
ERROR: Failed to delete branch. Aborting...
> Error: Command failed: git branch -d hello
> error: The branch 'hello' is not fully merged.
> If you are sure you want to delete it, run 'git branch -D hello'.
```
AFTER:
```
ERROR: Failed to delete branch. Aborting...
error: The branch 'asdf' is not fully merged.
If you are sure you want to delete it, run 'gt branch delete -f asdf'.
```
=> fix: improve branch deletion error message and change force arg to -f

src/actions/create_branch.ts, src/actions/fix.ts, src/actions/onto/stack_onto.ts, src/wrapper-classes/branch.ts, src/wrapper-classes/metadata_ref.ts
I was wrong about `prevRef` — that field does something different (tracks what the head of this branch was before, not what revision it was based on).  So we'll use a different field for tracking the base rev.
=> feat: start tracking branch parent revision in meta

src/actions/submit/submit_prs.ts, src/lib/sync/pr_info.ts, src/wrapper-classes/branch.ts, test/fast/commands/branch/branch_create.test.ts
I filed a linear to make the submit endpoint consistent with the prInfo endpoint, but for now this will do.
=> fix: don't overwrite PR info fields on update

src/actions/interactive_checkout.ts, src/wrapper-classes/stack.ts
=> fix: direction of bco interactive

src/actions/submit/pr_draft.ts, src/actions/submit/submit.ts, src/commands/shared-commands/submit.ts
Big change here is to not un-publish submitted PRs.  Also ensures that we never prompt for reviewers in non-interactive mode even if `-r` is passed.
=> feat: fix non-interactive submit

.CHANGELOG.md, scripts/demo/abstract_demo.ts, scripts/demo/full_demo.ts, scripts/demo/index.ts
we used to do `##` looks like we stopped by accident at some point.  it formats better on github
=> chore: fix changelog formatting

package.json, yarn.lock
source: https://yarnpkg.com/package/pre-commit
this is a package that automatically runs arbitrary yarn scripts as precommit hooks.  adding it to the CLI repo so that we have to dogfood hook support :)
=> chore: add precommit hooks

src/actions/fix.ts, src/actions/submit/validate_branches.ts, src/actions/validate.ts, src/commands/downstack-commands/validate.ts, src/commands/stack-commands/test.ts, src/commands/stack-commands/validate.ts, src/commands/upstack-commands/validate.ts, src/lib/errors.ts
I know storing the fix state in the validation exception is not a good pattern, but it seemed like cleanest way to reuse the validation code for now.  This will change upstack as we change how we do validation.
=> refactor: clean up validation some more

src/actions/sync/clean_branches.ts, src/actions/sync/sync.ts, src/lib/engine/cache.ts, src/lib/engine/cached_meta.ts, src/lib/runner.ts
Some of the invariants that this helper enforces revealed bugs in repo sync that caused test failures — since the stack is in a place where we are keeping tests passing, I chose to include the bug fixes in this PR as well.
=> refactor: move some core cache logic to a helper

src/background_tasks/post_survey.ts, src/background_tasks/upgrade_prompt.ts, src/commands/auth.ts, src/commands/demo.ts, src/commands/dev-commands/cache.ts, src/commands/repo-commands/repo_init.ts, src/commands/user-commands/branch_date.ts, src/commands/user-commands/branch_prefix.ts, src/commands/user-commands/branch_replacement.ts, src/commands/user-commands/editor.ts, src/commands/user-commands/tips.ts, src/lib/config/compose_config.ts, src/lib/context.ts, src/lib/runner.ts, src/lib/telemetry/sigint_handler.ts, src/lib/utils/branch_name.ts, test/lib/scenes/abstract_scene.ts
Adds a contextLite that we use instead of context when we don't need repo info.  should also make those commands faster.  learning that typescript is pretty good at letting you keep refactors small across the rest of the codebase as long as you have one place that you're ok with hiding the poop
=> feat: allow auth and user commands to be run outside of a repo

src/actions/edit/edit_downstack.ts, src/actions/test.ts, src/lib/config/repo_config.ts, src/lib/debug_context.ts, src/lib/engine/cache.ts, src/lib/engine/metadata_ref.ts, src/lib/git/branch_move.ts, src/lib/git/commit_range.ts, src/lib/git/commit_tree.ts, src/lib/git/delete_branch.ts, src/lib/git/detect_unsubmitted_changes.ts, src/lib/git/diff.ts, src/lib/git/fetch_branch.ts, src/lib/git/find_remote_branch.ts, src/lib/git/get_sha.ts, src/lib/git/is_merged.ts, src/lib/git/merge_base.ts, src/lib/git/prune_remote.ts, src/lib/git/pull_branch.ts, src/lib/git/push_branch.ts, src/lib/git/rebase.ts, src/lib/git/set_remote_tracking.ts, src/lib/git/show_commits.ts, src/lib/git/switch_branch.ts, src/lib/git/write_branch.ts, src/lib/utils/escape_for_shell.ts, test/fast/graphite_utils/escape_for_shell.test.ts
q is for quote, singlechar function name seems fine to me given we're only calling it in execsync and its clear from the import what it does
=> fix: escape literally everything

src/lib/engine/parse_branches_and_meta.ts
**Context:**
I noticed this bug while working on the upstack PR -- merge-base returns a revision, so this condition would never be true.
See single line change
**Test Plan:**
Tested locally.
=> fix: autofix of parent revision

src/lib/engine/parse_branches_and_meta.ts
**Context:**
User reported bug where after a manual rebase, track/metadata was wacky.
This is because if you have a case where
```
commit 2 - branch B
commit 1 - branch A
```
and you, without graphite, add `commit 1.5` to `branch A` and `git rebase --onto A B~1 B`
then the PBR of B would still be `commit 1`. Graphite would see it as valid because the history looks like:
```
commit 2 - branch B
commit 1.5 - branch A
commit 1
```
and `commit 1` is still in the history of `branch B`, but would show `(needs restack)` because the PBR doesn't match the current commit of `branch A`.  Restacking would just result in a noop.
This bug is due to the incorrect implicit assumption that updating a branch would always result in the old version not being in its history; …
=> fix: update parent revision in case where we are based on FF of old parent

src/commands/feedback-commands/default.ts, src/lib/git/commit_tree.ts
**Context:**
Users were seeing a git fatal when trying to submit feedback with a debug context, due to a bug in the way we quote/escape strings for git calls.
Fix the bug by adding spaces outside of quotes.
**Test Plan:**
Tested the full flow locally.
=> fix: feedback submission

src/actions/submit/submit_action.ts
**Context:**
v0.19 inadvertently broke `gt ss` from main because we were including trunk in the list of branches to submit
filter out trunk from the list of branches
**Test Plan:**
=> fix: allow gt ss from main

src/commands/feedback-commands/default.ts, src/lib/debug_context.ts, src/lib/git/commit_tree.ts
**Context:**
When testing the debug context flow, I realized that we were accidentally persisting a graphite cache for the repo the command was run from to the temp folder.
Just add the correct chdir to fix this, I think we can probably make this flow not require running in a repo but the command currently does multiple things.
**Test Plan:**
tested locally
=> fix: feedback state recreation

src/actions/untrack_branch.ts
Before they would hit e.g. "main is not tracked by Graphite"
=> feat: better error message for trunk in untrack

src/actions/sync/sync.ts, src/actions/untrack_branch.ts
Before this `--restack` wouldn't restack all branches as one would expect if run from trunk
=> fix: --restack on repo sync from trunk

src/actions/submit/prepare_branches.ts, src/actions/submit/submit_action.ts, src/commands/branch-commands/submit.ts, src/commands/downstack-commands/submit.ts, src/commands/shared-commands/submit.ts, src/commands/stack-commands/submit.ts, src/commands/upstack-commands/submit.ts
[Linear ticket](https://linear.app/screenplay/issue/GT-3848/change-submit-no-draft-to-publish-p)
**Context:**
**Test Plan:**
```
╭─ ~/graphite-cli jgb-3848 *1 
╰─❯ yarn cli stack submit --publish                                                                                                                                                                                                                                             ─╯
🥞 Validating that this Graphite stack is ready to submit...
✏️  Preparing to submit PRs for the following branches...
▸ jgb-3848 (Update)
📨 Pushing to remote and creating/updating PRs...
jgb-3848: https://app.graphite.dev/github/pr/withgraphite/graphite-cli/1081 (updated)
```
(Manually verified that this then moved the PR from …
=> Add publish arg

src/lib/engine/cache.ts, src/lib/engine/cache_loader.ts, src/lib/engine/cached_meta.ts, src/lib/engine/metadata_ref.ts, src/lib/git/get_sha.ts, src/lib/spiffy/cache_spf.ts
**Context:**
There's really no reason to store the meta cache in git refs.  Let's just use spiffy.
Replace the cache and cache key refs with a single spiffy.
**Test Plan:**
existing and local tests
=> refactor: cache to spiffy

src/actions/track_branch.ts, src/commands/branch-commands/track.ts, test/fast/commands/branch/track.test.ts
**Context:**
User pointed out it makes sense to have an option to pick most recent branch as parent
Add --force/-f as a way to not have to go through interactive selection, just pick the most reasonable default parent (most recent ancestor)
**Test Plan:**
added UT
=> feat: branch track --force

src/actions/rename_branch.ts
Accidentally included some symbols in the prompt
=> fix: formatting on branch rename interactive flow

src/actions/rename_branch.ts, src/lib/engine/cache.ts
**Context:**
Found the rename bug while I was working on the next PR — bug was that we would include the old name in the cached list of children we store in the metaCache of the parent of the renamed branch
Remove the old branch name from the cached children of its parent
**Test Plan:**
it works now
=> fix: bug with branch rename cached children

src/actions/fold_branch.ts, src/actions/submit/prepare_branches.ts, src/commands/branch-commands/fold.ts, src/lib/engine/cache.ts, test/fast/commands/branch/branch_fold.test.ts
First change is for update — bug was that if no args were passed, we would publish drafts on update.
Second change is for create — bug was that if no args were passed, we would always publish.
=> fix: draft publish logic on submit

src/actions/log.ts, src/commands/log-commands/default.ts, src/commands/log-commands/short.ts
remove the coloring — white looks good now that we have colors on the branch names
=> feat: change styling for needs restack in ls

src/background_tasks/post_traces.ts, src/background_tasks/upgrade_prompt.ts, src/lib/utils/git_repo.ts, src/lib/utils/spawn.ts
simpler than what I was trying to figure out earlier, but should work for most cases:
the `SHOULD_REPORT_TELEMETRY` flag just checks if `process.NODE_ENV == 'development'` which I suspect may be true for those that install with npm in a single repo
the node -> process.argv[0] thing should also solve in many cases
=> fix: background processes

src/actions/submit/submit_action.ts
this try catch is from before we moved to CommandFailed error, it will be handled correctly by the top level error handler, but lets leave the hint
=> fix: submit

src/actions/split.ts, src/commands/branch-commands/untrack.ts
as title — this will still prompt before execution if this branch has children
=> feat: untrack should untrack the current branch by default

scripts/node_version.js
**Context:**
The script that checks node version wasn't compatible with Node < 14 -_-
Remove instance of optional chaining (?. for compat)
**Test Plan:**
=> fix: version check script

src/actions/submit/pr_body.ts, src/actions/submit/pr_title.ts, src/actions/submit/prepare_branches.ts, src/actions/submit/submit_action.ts, src/commands/shared-commands/submit.ts, test/actions/submit_action.test.ts
**Context:**
Provide a way to avoid being prompted about editing changes and just
have the editor opened.
* Update `--edit/--no-edit` to have 3 states:
* When `--edit` is provided, the prompt to edit the description will
be skippped and an editor will be opened automatically for a PR
description.
* When `--no-edit` is provided, the prompt to edit the description
will be skipped and the default will be used.
* When neither option is provided, the user will be prompted for
whether to edit the description or use the default.
**Test Plan:**
* Updated existing tests.
* Verified locally.
=> feat: use edit flag to skip prompts

src/actions/submit/prepare_branches.ts
**Context:**
https://linear.app/screenplay/issue/GT-6155/communitybug-should-prompt-right-after-branch-name-in-submit
Currently when we are submitting a stack, we first determine the list of actions to perform and print the output for each step, and then we actually get the information for each action that needs additional info. This causes us to ask for information for a branch action away from when the actual action is outputted to the screen, causing confusion for users.
Let's move getting submission information inline to when we determine the action instead of getting all the submission information after getting getting all the actions. 
**Test Plan:**
```
ngobrendan@ip-192-168-86-48 /Users/ngobrendan/graphite/graphite-cli[10-27-step_2] yarn cli ss
🥞 …
```
=> fix: get submission info for actions inline

src/actions/log.ts, src/actions/log_short_classic.ts, src/actions/show_branch.ts
After a few months away from `gt` cli, I kind of forgot how to get a restack to occur. From the main help page, it's not clear that `restack` is a subcommand of `upstack` so this change makes it more clear _how to achieve a restack_ whenever the cli is recommending one. 
```
Commands:
gt auth                 Add your auth token to enable Graphite CLI to create
and update your PRs on GitHub.
gt branch <command>     Commands that operate on your current branch. Run `gt
branch --help` to learn more.             [aliases: b]
gt changelog            Show the Graphite CLI changelog.  [aliases: changelog]
gt commit <command>     Commands that operate on commits. Run `gt commit
--help` to learn more.                    [aliases: c]
gt completion           Set up bash or zsh tab completion.
gt …
```
=> clarify upstack message

apps/cli/src/actions/submit/pr_body.ts
**Context:**
We were treating editing Markdown PR descriptions as the Git commit format inside of `EDITOR`. This is causing bad validations and syntax error highlighting in many cases when writing PR descriptions–namely, if the first line is more than 50 chars in length.
From Slack:
> When using vim as gt editor - inherited from being git editor - and editing the PR body, it is started in a mode where it things it is used to edit a commit message.
> This causes it for example to show the first 50 characters of the first line in yellow and the second line with a red background,
> to remind that the subject should be short and that there has to be an empty line between subject and body.
> But while just editing a body, this is meaningless and more disturbs greatly
**Changes In This Pull …
=> Rename EDIT_DESCRIPTION to have an .md extension for better syntax highlights

apps/gti-client/src/CommitInfoView/CommitInfoView.tsx
we do this differently from ISL, (no local concept of draft status)
=> fix: dont show draft checkbox when creating a new branch
